### ISSUE TITLE
亿点点建议

### ISSUE THREAD

**Issue by Macesuted012** [extend-luogu/extend-luogu#104]
- [x] 希望能**美化设置界面**，并将设置默认语言改为简体中文《（since `VER 4.0.0`）
- [ ] 性能优化
- [ ] 希望能解决部分情况下设置**模块全开** exlg 按钮消失、控制台报错、重装也救不了的问题《未复现，请求控制台日志等详细信息

**Comment by william-song-shy** [comment]
1. 为了保证 exlg 继续存在，无法内置，但您可以使用 <https://greasyfork.org/zh-CN/scripts/406636-%E6%B4%9B%E8%B0%B7%E5%B9%BF%E5%91%8A%E5%B1%8F%E8%94%BD>
2. 已经是计划的一部分
3. 请您具体描述，目前无法复现大规模卡顿
4. 玄学问题，麻烦您反馈 F12 Console 中的消息
