### ISSUE TITLE
编辑剪贴板时无表情输入；命令行打开似乎有延迟；加入刷新犇犇按钮

### ISSUE THREAD

**Issue by xkh01** [extend-luogu/extend-luogu#107]
- [x] [bug] 在创建剪贴板的时候有表情输入，然而在编辑剪贴板的时候没有。
- [x] [bug] 在某些情况按 "/" 不会迅速弹出，我在用户主页和消息通知里遇到过。感觉完全可以改成只要焦点没在输入框都会弹出来好吧。<< fixed since `VER 4.1.2 Refix crash when any module throws`
- [x] [enhancement] 建议在犇犇旁边添加刷新按钮，优化刷全网动态时的体验。

**Comment by 5ab-juruo** [comment]
> 1. 在创建剪贴板的时候有表情输入，然而在编辑剪贴板的时候没有。

刻意设计，编辑是否出现是bug，是匹配的问题。

> 2. 在某些情况按 "/" 不会迅速弹出，我在用户主页和消息通知里遇到过。感觉完全可以改成只要焦点没在输入框都会弹出来好吧。

是神秘的一个 module 坏掉了就终止机制，而那个坏掉的 module 也是匹配的问题。

> 建议在犇犇旁边添加刷新按钮，优化刷全网动态时的体验。

会加的。

**Comment by xkh01** [comment]
> > 1. 在创建剪贴板的时候有表情输入，然而在编辑剪贴板的时候没有。
> 
> 刻意设计，编辑是否出现是bug，是匹配的问题。
> 
> > 2. 在某些情况按 "/" 不会迅速弹出，我在用户主页和消息通知里遇到过。感觉完全可以改成只要焦点没在输入框都会弹出来好吧。
> 
> 是神秘的一个 module 坏掉了就终止机制，而那个坏掉的 module 也是匹配的问题。
> 
> > 建议在犇犇旁边添加刷新按钮，优化刷全网动态时的体验。
> 
> 会加的。

事实证明只需要再点一次“全网犇犇”那个按钮就会刷新啊

**Comment by xkh01** [comment]
在用户主页似乎可以直接跳出来，但是在通知界面压根出不来
