### ISSUE TITLE
插件加载速度过慢

### ISSUE THREAD

**Issue by YOYO-UIAT** [extend-luogu/extend-luogu#109]
每次开洛谷主页都要加载好久才能加载出来 exlg，其他页面没有这个问题。

**Comment by 5ab-juruo** [comment]
主页犇犇表情需要加载。

**Comment by YOYO-UIAT** [comment]
我把所有表情都关了也很慢，况且表情都挂了

**Comment by YOYO-UIAT** [comment]
F12 查出来了，是 图.tk 挂了，希望能修一下

**Comment by YOYO-UIAT** [comment]
草，360 还是算了

谢谢了

**Comment by ForkKILLET** [comment]
@YOYO-UIAT 进入 `图.tk` 选择继续访问应该能解决此问题。高版本 chromium 内核在页面上敲击 `thisisunsafe` 也行。

**Comment by YOYO-UIAT** [comment]
@ForkKILLET 

> This XML file does not appear to have any style information associated with it. The document tree is shown below.

这咋整

**Comment by ren-yc** [comment]
> @ForkKILLET
> 
> > This XML file does not appear to have any style information associated with it. The document tree is shown below.
> 
> 这咋整

就是这样，现在换了 Github 镜像表情源，更新就没问题了。
