### ISSUE TITLE
插件设置页面无法翻页

### ISSUE THREAD

**Issue by wangr-x** [extend-luogu/extend-luogu#110]
本人 NOI linux  
firefox 浏览器下，exlg 设置页面无法翻页，只能通过 ctrl+鼠标滚轮缩放页面设置。  
edge 浏览器下一切正常。  
希望能增强对 firefox 的支持

**Comment by optimize-2** [comment]
请详细描述“无法翻页”
是说 modules 无法滚动吗
新版设置界面本来就只有一页

**Comment by wangr-x** [comment]
modules 无法滚动

**Comment by optimize-2** [comment]
15 Feb 就修复了为啥没人关啊
