### ISSUE TITLE
存储代理加载失败

### ISSUE THREAD

**Issue by ybw051114** [extend-luogu/extend-luogu#112]
rt

**Comment by ForkKILLET** [comment]
1. 如果没什么重要数据：油猴图标 -> extend-luogu 小箭头 -> 编辑 -> 存储标签页 -> 把文本框清空，改成 `{}`
2. 截图一下控制台报错

**Comment by dajia-1701** [comment]
![image](https://user-images.githubusercontent.com/48874489/154714012-22f47816-8714-4c93-b868-86c04ae19d74.png)
@[ForkKILLET](https://github.com/ForkKILLET)

**Comment by dajia-1701** [comment]
@ForkKILLET

**Comment by 5ab-juruo** [comment]
是 TM_dat 更新的问题，刷新几次就能解决了。
