### ISSUE TITLE
建议改用 啧.tk 作为表情包

### ISSUE THREAD

**Issue by ren-yc** [extend-luogu/extend-luogu#114]
啧.tk 支持 `https://啧.tk/QQ 表情代号`，建议 exlg 能在输入 `/QQ 表情代号` 时自动转化为前面的链接形式。

~~同样，图.tk 也可以暂时不用了~~

**Comment by johnvp22** [comment]
我提交了一个pr，先用github放一下表情包。
这个好像是他们写了但是锅了？

**Comment by ren-yc** [comment]
> 我提交了一个pr，先用github放一下表情包。 这个好像是他们写了但是锅了？

我之前也 PR 了一个（捂脸）
