### ISSUE TITLE
dashboard在firefox无法滚动

### ISSUE THREAD

**Issue by gsh20040816** [extend-luogu/extend-luogu#116]
![图片](https://user-images.githubusercontent.com/54617983/151746479-aafb9676-6097-408f-8ea9-5c09f114947f.png)
### edge可以正常滚动

![图片](https://user-images.githubusercontent.com/54617983/151746524-587200ce-50cb-473b-baf2-95829aacf00b.png)
### firefox无法滚动

**Comment by ren-yc** [comment]
拖动旁边的滚动轴？

**Comment by gsh20040816** [comment]
没法拖动

**Comment by ForkKILLET** [comment]
已复现，应该火速能修

**Comment by ForkKILLET** [comment]
fixed，部署完就能滚动了
