### ISSUE TITLE
无法 Vp 比赛

### ISSUE THREAD

**Issue by HappyCodeHC** [extend-luogu/extend-luogu#123]
RT，v4.2.5，更新前没问题

**Comment by HappyCodeHC** [comment]
艹issues123

**Comment by 5ab-juruo** [comment]
luogu api 更新的缘故导致的，目前由于某些原因暂时 push 不了，如果不嫌麻烦可以将第 2169 行的 `resp.status` 改成 `resp.status ?? 200`，或每次重建完毕后手动进入比赛界面查看。
