### ISSUE TITLE
表情图片无法加载

### ISSUE THREAD

**Issue by zhk1211** [extend-luogu/extend-luogu#126]
<img width="831" alt="iShot2022-02-13 17 03 19" src="https://user-images.githubusercontent.com/60701418/153746295-aa06fa1c-edbb-41fc-bf38-e5c4cbc9f7b8.png">

**Comment by ForkKILLET** [comment]
脚本 25 行 `@main` 改为 `@0.8.3` 以手动更新 TM-dat，更新后可能会清存，重要数据做好备份
