### ISSUE TITLE
关于图片源的优化

### ISSUE THREAD

**Issue by EarthMessenger** [extend-luogu/extend-luogu#129]
现在（2022年2月20日），exlg 统共有四个图片加载源：
1. `图.tk`
2. `妙.tk`
3. `啧.tk`
4. `cdn.jsdelivr.net`

`图.tk` 和 `妙.tk` 加载速度较慢；`啧.tk` 是国内节点较稳定，但没有充足的图片；`cdn.jsdelivr.net` 由于备案的问题中国内的速度较慢（#jsdelivr/jsdelivr#18367）。

可以考虑加上加上负载均衡，统一使用一个域名，再根据 ip/地区 跳转到对应的源。如国内走 `啧.tk`，国外走 jsdelivr，等 jsdelivr 好之后统一 jsdelivr（免费又快速）。

针对 jsdelivr 还可以添加 `testingcf.jsdelivr.net`，`fastly.jsdelivr.net`，`gcore.jsdelivr.net` 等域名。也可以将 extend-luogu 作为包发到 npm 上，再用 unpkg 加速（unpkg 拥有丰富的国内镜像如百度，知乎），添加更丰富的加载源。

**Comment by 5ab-juruo** [comment]
没必要，洛谷的大部分受众是中国用户，且链接是存储在洛谷服务器中无法修改。

**Comment by EarthMessenger** [comment]
正因为中国用户居多，因此才考虑更改。

cdn.jsdelivr.net 在某些国内地区（如我所在的地区）是最慢的，加载单个图片最多可以超过 10s，而有时其它域名会快一些（总之十分玄学）。用户使用不同的加载源，最后在某些地区看得到，某些地区看不到，显然不好。

使用负载均衡，统一到一个域名，既有利于浏览器本地缓存，又可以防止某些用户脑残用了劣质源导致其他地区看不到，还可以简化 userscript 代码。

**Comment by 5ab-juruo** [comment]
默认不是 jsdelivr，且只要 图.tk 不炸也没有人会去用其它源，而且现在的问题是域名的 https 证书不稳定而非负载。

**Comment by ForkKILLET** [comment]
这里有一个小问题，就是我们未必舍得花钱（不是）

目前访问速度还是很快的，主要是 https 的问题
