### ISSUE TITLE
可疑代码识别错误

### ISSUE THREAD

**Issue by xjrjyy** [extend-luogu/extend-luogu#136]
`chrono::system_clock` 会被识别成可疑代码

**Comment by 5ab-juruo** [comment]
现阶段这个东西只是简单的字符串匹配，需要进一步的完善和训练。

进一步的检查可能要 parser 了，那就不是这个级别的项目能做得到的了。

**Comment by 5ab-juruo** [comment]
如果难以忍受的话，可以在设置中降低检查强度
