### ISSUE TITLE
LaTeX 自动排版功能

### ISSUE THREAD

**Issue by 5ab-juruo** [extend-luogu/extend-luogu#137]
题解提交前预审核功能审核内容：

- [x] LaTeX 公式和中文之间要有空格；
- [x] LaTeX 公式和标点符号之间不要空格；
- [ ] LaTeX 公式中不能出现 “*” “/” 符号；
- [x] 中文英文之间要有空格；
- [x] 英文符号之间不要空格；（合理性待定）
- [ ] 不可以滥用标题行（多次出现一级标题）。

**Comment by YuzhenQin** [comment]
#144

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
https://www.luogu.com.cn/paste/z3aw2tvt

个人关于「滥用标题行」的界定（）是否是合理的？

**Comment by 5ab-juruo** [comment]
@YuzhenQin 请加上对你后端的说明。
