### ISSUE TITLE
主页展示的帖子部分消失

### ISSUE THREAD

**Issue by NFLSCode** [extend-luogu/extend-luogu#141]
## 复现
开启exlg：
![Screenshot 2022-03-27 at 17-21-06 首页 - 洛谷 计算机科学教育新生态.png](https://s2.loli.net/2022/03/27/8KDVQOfBIuodkcT.png)

关闭exlg：
![Screenshot 2022-03-27 at 17-21-29 首页 - 洛谷 计算机科学教育新生态.png](https://s2.loli.net/2022/03/27/hZr3UtcbNQvy7nX.png)

**Comment by ren-yc** [comment]
@NFLSCode exlg 有自动缩小讨论区帖子数量的，可以在设置中关闭。

**Comment by ren-yc** [comment]
@NFLSCode #80
