### ISSUE TITLE
用户备注变成空白无法改回

### ISSUE THREAD

**Issue by NFLSCode** [extend-luogu/extend-luogu#142]
复现方法：
在犇犇中选中人名，再右击，再取消更改备注，备注就会变成空白（空格？），无法选中
```
<a class="lg-fg-red lg-bold exlg-badge-username exlg-usercmt" href="/user/572482" target="_blank" uid="572482" cardid="290"></a>
```
（名字部分的html代码）

![Screenshot 2022-03-27 at 19-10-38 首页 - 洛谷 计算机科学教育新生态.png](https://s2.loli.net/2022/03/27/Dlow8WjfGLC54mY.png)
（截图）

**Comment by 5ab-juruo** [comment]
@NFLSCode 请使用最新版，经测试是不会出现这种问题的。

**Comment by 5ab-juruo** [comment]
怎么还有锅，完了

**Comment by 5ab-juruo** [comment]
修好了，使用 >=5.5.1 即可。
