### ISSUE TITLE
使用命令行进行页面跳转的 bug

### ISSUE THREAD

**Issue by xkh01** [extend-luogu/extend-luogu#143]
比如，在[这个页面](//coder6886.blog.luogu.org/p8255)执行 `/cdd ra`，那么页面会跳转到 `https://coder6886.blog.luogu.org/discuss/lists?forumname=relevantaffairs`…… 其他也是…… 而且在博客有些命令无法使用还没修。。

**Comment by ForkKILLET** [comment]
啊行

**Comment by ForkKILLET** [comment]
`cdd` 修了
