### ISSUE TITLE
代码块优化导致 Dark Reader 失效

### ISSUE THREAD

**Issue by APJifengc** [extend-luogu/extend-luogu#147]
代码块优化会让代码块重新渲染，然后就会使暗色的代码块又变成亮色，每次都要把 Dark Reader 关掉重新开：/

![](https://user-images.githubusercontent.com/55266764/160726849-d3543ff3-313d-49a9-bcfa-fcac6e7e0e18.png)

**Comment by 5ab-juruo** [comment]
这是什么功能，如果是浏览器考虑做兼容，否则不太可能修，请具体描述。

**Comment by Minstdfx** [comment]
这样，我加一个自定义背景色功能，行不？

**Comment by YuzhenQin** [comment]
已经在 Commit `c311026d17fb107d92b3d4f0525b9d04a3921133` 中被修复。
