### ISSUE TITLE
点击复制按钮没有复制？

### ISSUE THREAD

**Issue by sunzhangchang** [extend-luogu/extend-luogu#150]
## 问题描述
RT

**Comment by YuzhenQin** [comment]
无法复现，请提供复现步骤

**Comment by sunzhangchang** [comment]
exlg v5.5.2 或 5.6.0

https://user-images.githubusercontent.com/52880063/160983208-4790c5ad-03e9-4853-a073-1ee4d03d3e62.mp4

**Comment by sunzhangchang** [comment]
我之前使用scriptcat，以为scriptcat没有GM相关的api。

但是我发现scriptcat也有GM_setClipboard等api，所以这可能不是scriptcat的问题

**Comment by optimize-2** [comment]
？
