### ISSUE TITLE
备注功能：姓名备注

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#154]
**如果有多个建议，请分别提出，不要扎堆。**

请在标题简单描述你的建议，然后提出你希望得到的效果，最好能附上参考的解决方案。

姓名请不要右键备注，当我们在用鼠标右键在新标签页中打开的时候，会弹出来一个备注框，非常烦。建议在用户界面，个人博客的左面位置添加一个姓名备注按钮。

希望姓名备注可以换一种形式：显示为 <原名称>（<备注名>）。若备注名里什么都没有，也请不要有括号，只显示成 <原名称>。例如：optimize_2（o2），optimize_2。这样可以避免某些人在一个人电脑上做一些操作，混淆很多人的名称，例如某人将两个头像一样的人改成一个备注名，这两个人就会一个都不认识。

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
wc label 标错了 是 bug

**Comment by 5ab-juruo** [comment]
请你解释这与 #155 的区别。

**Comment by wxh06** [comment]
> 请你解释这与 #155 的区别。

他的意思应该是一个是“备注用来标识用户的名字”（相当于微信里的“备注名”），一个是用来记录一些对于用户的信息（相当于微信里的“添加更多备注信息”）
比如“姓名备注”是“o2”，而“用户备注”是“exlg创始人”

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
> 请你解释这与 #155 的区别。

https://cdn.luogu.com.cn/upload/image_hosting/w61ranqf.png 名字后面的是这里的内容，而右下角才是 #155 的内容。

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
> > 请你解释这与 #155 的区别。
> 
> 他的意思应该是一个是“备注用来标识用户的名字”（相当于微信里的“备注名”），一个是用来记录一些对于用户的信息（相当于微信里的“添加更多备注信息”） 比如“姓名备注”是“o2”，而“用户备注”是“exlg创始人”

差不多对，但是还差一点。用户备注相当于“记仇本子”，可以记 x 月 x 日 xxx ak 了 ioi，x 月 x+1 日 xxx 吊打了我，x 月 x+2 日题解被打回了之类的。
