### ISSUE TITLE
备注功能：用户备注

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#155]
用户备注和姓名备注不同，姓名备注是改了用户一个你熟悉的名字，而用户备注则是建立了一个小本本用来记仇（什么奇妙的比喻）。

希望可以在“用户编号 用户类型 注册时间”那个框下面新增一个框作为用户备注。

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
> 可以理解要在用户界面显示你的备注。
> 
> 不太理解两个备注有什么不同。

https://cdn.luogu.com.cn/upload/image_hosting/w61ranqf.png 右下角的是这里的效果，名字后面是 #154 的效果。

**Comment by eventlOwOp** [comment]
没有必要, 你可以在名字后面打个括号, 功能冗余不符合开发哲学
