### ISSUE TITLE
请在标题简单描述你的问题

### ISSUE THREAD

**Issue by HappyCodeHC** [extend-luogu/extend-luogu#156]
**如果有多个问题，请分别汇报，不要扎堆。**

## 问题描述
请修改标题。

## 复现
请描述你是怎么遇到这个问题的，尽可能详细以便于管理复现。

如果方便的话，建议附上截图。

## 环境
请描述你使用的浏览器，系统信息，大多时候不是必须的。

验证码貌似填的不准哎，另外自动填验证码不符合规则吧，容易出来广告 bot  
4z4k 填成 444k

**Comment by optimize-2** [comment]
操你妈

**Comment by optimize-2** [comment]
你家验证码能被 AI 100% accuracy 吗
