### ISSUE TITLE
请在标题简单描述你的问题

### ISSUE THREAD

**Issue by HappyCodeHC** [extend-luogu/extend-luogu#157]
**如果有多个问题，请分别汇报，不要扎堆。**

## 问题描述
请修改标题。

## 复现
请描述你是怎么遇到这个问题的，尽可能详细以便于管理复现。

如果方便的话，建议附上截图。

## 环境
请描述你使用的浏览器，系统信息，大多时候不是必须的。

验证码貌似填的不准哎，另外自动填验证码不符合规则吧，容易出来广告 bot  
4z4k 填成 444k

之前发的 [#156](https://github.com/extend-luogu/extend-luogu/issues/156) 为啥没回复就被 Closed 了

**Comment by HappyCodeHC** [comment]
@optimize-2

**Comment by ren-yc** [comment]
您以为这功能是直接黑进 lg 服务器获取验证码 ans 的啊？

**Comment by ForkKILLET** [comment]
你会用 issue template 吗

**Comment by ForkKILLET** [comment]
什么规则？哪一条哪一款？能管到 exlg 吗？

**Comment by wxh06** [comment]
觉得不好用就别用，在控制面板里关掉
本来我做出来就只是一个小工具，又不是为了100%准确率让你免验证码的

**Comment by HappyCodeHC** [comment]
> 你会用 issue template 吗

咋用啊
