### ISSUE TITLE
一些小建议（如果可行的话）

### ISSUE THREAD

**Issue by ACS-resources** [extend-luogu/extend-luogu#159]
- [ ] #234
- [ ] 2. 自定义显示在左侧标签栏的按钮（比如讨论、统计等按钮）
- [ ] 3. CE后返回的代码错误信息多彩化

**Comment by wxh06** [comment]
> **如果有多个建议，请分别提出，不要扎堆。**

感谢您宝贵的建议，但是这边还是希望您能分开 issue 呢！

**Comment by ACS-resources** [comment]
好的！谢谢exlg开发组对洛谷社区和OIer的帮助！:)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "extend-luogu/extend-luogu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月1日(星期五) 下午2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [extend-luogu/extend-luogu] 一些小建议（如果可行的话） (Issue #159)





  
如果有多个建议，请分别提出，不要扎堆。
  
感谢您宝贵的建议，但是这边还是希望您能分开 issue 呢！

**Comment by 5ab-juruo** [comment]
1 较难做到，建议使用 luogulo.gq 的帖子搜索功能。

其余将会考虑。

**Comment by ACS-resources** [comment]
好的！谢谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月2日(星期六) 晚上11:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [extend-luogu/extend-luogu] 一些小建议（如果可行的话） (Issue #159)





 
1 较难做到，建议使用 luogulo.gq 的帖子搜索功能。
 
其余将会考虑。

**Comment by 5ab-juruo** [comment]
经过开发组内部讨论，我们认为您所说的功能没有特别价值，故不予实现。
