### ISSUE TITLE
犇犇页面加上管理 tag

### ISSUE THREAD

**Issue by chenzheAya** [extend-luogu/extend-luogu#161]
被迫动用了自己尘封的 github 号（

没有管理 tag 的话感觉不太好看（，包括其他有洛谷官方 tag 的用户少了总感觉缺点内味（

**Comment by ren-yc** [comment]
惊现 cz！😮

**Comment by 5ab-juruo** [comment]
有没有一种可能，exlg badge 和官方 tag 轮流出现（

**Comment by Minstdfx** [comment]
这个不归我管（

**Comment by william-song-shy** [comment]
就是说理论上是有的

https://github.com/extend-luogu/extend-luogu/blob/9e8585a3a7e750b55f9acfea2ed21566556a685b/src/modules/benben.js#L56

不知道为什么加载不出来

**Comment by william-song-shy** [comment]
审查了代码并做了相关实验，并没有发现相关问题
