### ISSUE TITLE
dropdown 美化和 exlg 按钮的显示错误

### ISSUE THREAD

**Issue by YuzhenQin** [extend-luogu/extend-luogu#162]
## 问题描述
![07L_{{SL 6H%J_}IQF{W7AV](https://user-images.githubusercontent.com/59137898/161408214-dc496429-5516-49ad-aebd-47d8ecc7b876.png) ![US%LJUH~S }}`HYDG_ VTF9](https://user-images.githubusercontent.com/59137898/161408217-3257bb00-3efd-4901-a761-47e01cb8748f.png)  
（ exlg 按钮也不会加载）

## 复现
在指定的页面点击头像，进入个人中心，然后点击浏览器的后退按钮，返回指定页面

## 环境
Windows 11 家庭中文版 22557.1 (Dev 通道)  
Google Chrome 版本 102.0.4972.0（正式版本）dev （64 位） & Mozilla Firefox 98.0.2 (64 位)  
Tampermonkey BETA v4.16.6159 (Chrome) & Tampermonkey v4.15.6154 (Firefox)  
extend-luogu 5.6.4

另附浏览器控制台log：  
[www.luogu.com.cn-1648952238210.log](https://github.com/extend-luogu/extend-luogu/files/8403678/www.luogu.com.cn-1648952238210.log)

**Comment by Minstdfx** [comment]
修好了，关了
