### ISSUE TITLE
更新到 5.6.7 后无法回到原版的头像 dropdown

### ISSUE THREAD

**Issue by H-J-Granger** [extend-luogu/extend-luogu#164]
**如果有多个问题，请分别汇报，不要扎堆。**

## 问题描述
请修改标题。

## 复现
请描述你是怎么遇到这个问题的，尽可能详细以便于管理复现。

将版本更新到 5.6.7 后鼠标 hover 到头像上方即可发现 dropdown 有更新。然而，在 <https://dash.exlg.cc/index.html> 内无法关闭这个功能。

如果方便的话，建议附上截图。

## 环境
请描述你使用的浏览器，系统信息，大多时候不是必须的。

**Comment by Minstdfx** [comment]
所以为什么要关呢

**Comment by H-J-Granger** [comment]
习惯了改不了（

不过我好像知道怎么关了，在 <https://dash.exlg.cc/index.html> 的控制桥那里

**Comment by Minstdfx** [comment]
草你这一关怕不是直接把按钮弄没了

**Comment by Minstdfx** [comment]
行吧行吧回头加上去
