### ISSUE TITLE
团队作业界面出现四个”随机跳题“

### ISSUE THREAD

**Issue by wood3** [extend-luogu/extend-luogu#168]
## 问题描述
在同时安装了 exLG 与 searchAnyWhere 的情况下，团队作业界面出现了”随机跳题“四重奏，猜测与 searchAnyWhere 刚出现时的 exlg 四重奏是同一个问题。

![image](https://user-images.githubusercontent.com/4684982/161883379-685b039a-0eb4-4962-9060-f9cc322f4410.png)

## 复现
创建一个团队作业，参与作业即可

## 环境
- exLuogu 5.7.0
- LuoguSearchAnywhere

**Comment by wxh06** [comment]
优秀 issue 典范 :thumbsup:

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
> ## 问题描述
> 在同时安装了 exLG 与 searchAnyWhere 的情况下，团队作业界面出现了”随机跳题“四重奏，猜测与 searchAnyWhere 刚出现时的 exlg 四重奏是同一个问题。
> 
> ![image](https://user-images.githubusercontent.com/4684982/161883379-685b039a-0eb4-4962-9060-f9cc322f4410.png)
> 
> ## 复现
> 创建一个团队作业，参与作业即可
> 
> ## 环境
> * exLuogu 5.7.0
> * LuoguSearchAnywhere

请更新你的 Extend-Luogu 和 LuoguSearchAnywhere 到最新版本。我的两个脚本都是最新的，没有这种问题。

![image](https://user-images.githubusercontent.com/56300237/161884719-1b2ef570-7134-4a50-a360-c1bcb9fec26b.png)

附上 LuoguSearchAnywhere 最新版本下载地址：https://greasyfork.org/users/829530

**Comment by YuzhenQin** [comment]
更正 lsaw 下载地址：[https://greasyfork.org/zh-CN/scripts/442416-luogu-search-anywhere](https://greasyfork.org/zh-CN/scripts/442416-luogu-search-anywhere)
