### ISSUE TITLE
建议缩短一些帖子的标题长度以保证格式

### ISSUE THREAD

**Issue by OldFishBall** [extend-luogu/extend-luogu#172]
![微信截图_20220408134550](https://user-images.githubusercontent.com/61718487/162373059-e79665c1-eb94-42ba-b37e-84f6d686b585.png)

如图，建议将第二个讨论的标题或发表的板块省略一部分，让一行内的帖子整齐。

**Comment by Minstdfx** [comment]
你会发现不是标题长度的问题

**Comment by Minstdfx** [comment]
是用户名+板块太长了，没法修
