### ISSUE TITLE
关于复制代码的两个建议

### ISSUE THREAD

**Issue by shenyouran** [extend-luogu/extend-luogu#180]
## 问题描述
需要在剪贴板复制代码时，必须展开整个剪贴板，否则只能复制到可见部分。例如在下面这种情况中只能复制到三行代码：

![A`48`}}LA5S)A4%OWR@QF(7](https://user-images.githubusercontent.com/60684241/162596878-0479b885-fc1c-488a-a72f-5978807db9e8.png)

另外，无论在哪里复制代码，粘贴时总会多出多余换行符。虽然这看起来没有什么影响，但每次都要删一下确实有点麻烦。

希望能尽快修复（~~你们的 release 速度好快~~），谢谢！

**Comment by 5ab-juruo** [comment]
1. 属于洛谷特性，收起来的时候剪贴板只会渲染一部分，不会修复。
2. 会修的。

**Comment by shenyouran** [comment]
> 1. 属于洛谷特性，收起来的时候剪贴板只会渲染一部分，不会修复。
> 2. 会修的。

谢谢！

**Comment by Minstdfx** [comment]
1. 属于洛谷特性，收起来的时候剪贴板只会渲染一部分，不会修复。
2. 代码块复制末尾出现空行为正常现象，方便直接粘贴插入到现有代码中。
