### ISSUE TITLE
关于exlg.frame的问题

### ISSUE THREAD

**Issue by little-cindy** [extend-luogu/extend-luogu#181]
## 问题描述
使用<iframe>打开网页后，显示的是bilibili.com的子域名（一般返回乱码，毕竟基本上不可能那么巧），显示不了原始网页
## 复现
在用户主页输入以下代码：
```html
exlg.frame: <iframe src="https://www.luogu.com.cn/"></iframe>
```
## 环境
- exlg ver6.0.0
- 油猴 ver4.15

**Comment by little-cindy** [comment]
开发方可以自己试一下

**Comment by little-cindy** [comment]
显示bilibili.com的子域就离谱

**Comment by optimize-2** [comment]
`exlg.frame:https://www.luogu.com.cn/`

**Comment by little-cindy** [comment]
谢谢
