### ISSUE TITLE
全网犇犇加载中切换到其他页面导致的错误

### ISSUE THREAD

**Issue by YuzhenQin** [extend-luogu/extend-luogu#191]
![GN3CX8LIFCYCXNPM5 1P0W](https://user-images.githubusercontent.com/59137898/163578566-263a01a1-9502-40eb-a8a8-bf5738545888.png)  
复现方法：首先点击 `全网犇犇`，加载出来之前切换到其他页面

**Comment by Minstdfx** [comment]
补充：洛谷原版的犇犇也能卡出来貌似

**Comment by william-song-shy** [comment]
这是原版特性
