### ISSUE TITLE
头像下的 dropdown 无法回退至旧版

### ISSUE THREAD

**Issue by H-J-Granger** [extend-luogu/extend-luogu#197]
## 问题描述
如题，将 <https://dash.exlg.cc/index.html> 内所有可取消选择的勾取消选择并不能关闭。

## 复现
尝试关闭 dropdown，发现没有办法关闭。

## 环境
exlg 版本：6.1.7

**Comment by wxh06** [comment]
请问您使用的是哪个版本？

**Comment by H-J-Granger** [comment]
> 请问您使用的是哪个版本？

6.1.7

**Comment by wxh06** [comment]
您是希望禁用 exlg 修改用户头像悬浮下拉菜单？
