### ISSUE TITLE
无法显示 badge

### ISSUE THREAD

**Issue by HappyCodeHC** [extend-luogu/extend-luogu#200]
Edge 100.0.1185.44 Tampermonkey 4.16 exlg 6.2.0/6.2.1-pre2

谁的 badge 都无法显示。  
与黑名单无关，用小号登录依然无法显示

upd：重置脚本无果

**Comment by wxh06** [comment]
UID 多少？

**Comment by HappyCodeHC** [comment]
546369  
544880

**Comment by wxh06** [comment]
544880 在服务器端没有任何数据

**Comment by HappyCodeHC** [comment]
我的意思是别人的 badge 无法显示

**Comment by HappyCodeHC** [comment]
我没有 badge

**Comment by wxh06** [comment]
服务器不曾有用户 544880 访问请求的记录

**Comment by wxh06** [comment]
> 你们 badge 的源地址是什么，我看一下能不能访问

参阅 https://github.com/extend-luogu/exlg-backend#overview

**Comment by HappyCodeHC** [comment]
我明天研究一下，知道了什么问题再来看

**Comment by optimize-2** [comment]
token 没有及时更新。你明天不用研究也会自己解决的。
