### ISSUE TITLE
与Luogu Tasks兼容

### ISSUE THREAD

**Issue by Deng-Duck** [extend-luogu/extend-luogu#201]
更新之后无法使用了__OwO__的Luogu Tasks了

https://greasyfork.org/scripts/424363/code/script.user.js

这个插件非常好用，所以我仍然想要使用它，但是Extend_Luogu也很好用，我全都要

希望可以兼容Luogu Tasks或直接出功能把它替代了

**Comment by YuzhenQin** [comment]
无法复现

**Comment by Deng-Duck** [comment]
本鸭回邮箱较慢，谢谢！

**Comment by YuzhenQin** [comment]
您尝试过修改 `inject_lantency` 吗
