### ISSUE TITLE
original-difficulty 存在三个点，但右键无反应

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#202]
**如果有多个问题，请分别汇报，不要扎堆。**

## 问题描述
「显示原始难度」这个模块理应是可以展开的，经查源代码发现可以进行更改 CF 题目源等操作，但是我在右键这个模块的时候无法展开这个模块。
![image](https://user-images.githubusercontent.com/56300237/164567038-79a42841-9e7b-45e3-b28a-671901438cc3.png)

## 复现
进入 gh-index 页面，找到「显示原始难度」模块，右键，可以发现无法展开。

## 环境
Chrome 版本：版本 100.0.4896.127（正式版本） （64 位）
系统版本：Windows 10 x64
装载脚本：Extend-Luogu 6.2.2（从 OSS 更新）；Luogu Search Anywhere；洛谷用户卡片。

**Comment by 5ab-juruo** [comment]
有个人把新的设置桥给注释掉了，我不说是谁。
