### ISSUE TITLE
新账号不能自动获取 token

### ISSUE THREAD

**Issue by Minstdfx** [extend-luogu/extend-luogu#203]
**如果有多个问题，请分别汇报，不要扎堆。**

## 问题描述
新账号不能自动获取 token

## 复现
登录从来没用过 exlg 的新账号，无法自动获取 token，需要手动在控制台中获取

## 环境
chrome win10-64

**Comment by 5ab-juruo** [comment]
新增了自动获取的按钮能解决这个问题吗。

**Comment by 5ab-juruo** [comment]
或许应该加一个设置，通过 chore 是否返回 false 来判断这次 chore 是否算数。
