### ISSUE TITLE
建议增加 “问题跳转” 栏宽度

### ISSUE THREAD

**Issue by ren-yc** [extend-luogu/extend-luogu#211]
### 问题描述

当 `随机跳题ex` 全半角字符之间增加空格时 `<button>` 会被挤到第二行，不美观。

![image](https://user-images.githubusercontent.com/53416099/165029989-26997d96-49d1-4f2a-9d5b-bd0fc26c6339.png)

### 复现

打开洛谷首页并启用 Stylus (Argon Luogu)。

### 环境

* Extend-Luogu 6.3.0

* Argon Luogu

**Comment by 5ab-juruo** [comment]
只要多了个按钮这种 ui 问题就是没法避免的。

**Comment by ren-yc** [comment]
对于 Argon Luogu 可行的方案是把 `<button>` 类的宽度设为 `17 px` 及以下。
