### ISSUE TITLE
建议增加 UVa 题库 level（原始难度）

### ISSUE THREAD

**Issue by Daijianghao** [extend-luogu/extend-luogu#216]
如题，CF 都有了 UVa 应该也很容易实现吧。

且 UVa 的题目大多大多在洛谷都没有评分，可以在 <https://www.luogu.com.cn/problem/list?type=UVA> 上直接加个和洛谷难度一样的 level 写旁边得了，这样在列表里找水无人题写题解时也能方便。

**Comment by 5ab-juruo** [comment]
CF 的题目是有评级的，而 UVa 暂不了解，若有请您提供，我们会立刻添加的。

**Comment by Daijianghao** [comment]
@5ab-juruo 因为使用 UVA Arena 的时候发现有 level [图片](https://cdn.luogu.com.cn/upload/image_hosting/tzvygk29.png)，项目可在 gathub 上搜到，我使用的是 v1.9。
然后顺藤摸瓜找到了 uHunt [link](https://uhunt.onlinejudge.org/)，它的介绍里说“能根据难度组织问题”，但似乎访问极差，动不动就 Error。
某度上似乎有 CSDN 博客，都是一模一样的 [baidu](https://www.baidu.com/s?ie=UTF-8&wd=UVA%E9%9A%BE%E5%BA%A6)。
更官方的好像没找到/dk，网站实在太慢了。

**Comment by 5ab-juruo** [comment]
这样看来可能增加会较为困难。

一方面，我并没有在 uHunt 上找到您描述的 Level 状物。另一方面，由于 exlg 并没有国外服务器，所以不能免费提供代理状物。

**Comment by optimize-2** [comment]
> 这样看来可能增加会较为困难。
> 
> 一方面，我并没有在 uHunt 上找到您描述的 Level 状物。另一方面，由于 exlg 并没有国外服务器，所以不能免费提供代理状物。

cloudflare

**Comment by YuzhenQin** [comment]
> > 这样看来可能增加会较为困难。
> > 一方面，我并没有在 uHunt 上找到您描述的 Level 状物。另一方面，由于 exlg 并没有国外服务器，所以不能免费提供代理状物。
> 
> cloudflare

显然地，uHunt 有源站限制，这就需要使用服务器或 Cloudflare Workers 进行代理，而 Cloudflare Workers 是有限制的。  
btw，我们这里有境外服务器。

**Comment by YuzhenQin** [comment]
在 UVA-Arena 的代码中我们发现下列代码：
```
const int MAX_LEVEL = 9;
this.Level = 1 + MAX_LEVEL;
if (this.dacu > 0)
{
    this.Level -= Math.Min(MAX_LEVEL, Math.Floor(Math.Log(this.dacu)));
}
```
即 Level 为 10 减去 9 和 通过人数的对数向下取整中的中的最小值

**Comment by Daijianghao** [comment]
> 

按照通过人数算的？那就算了。
