### ISSUE TITLE
题目和题解自动审核排版功能

### ISSUE THREAD

**Issue by Daijianghao** [extend-luogu/extend-luogu#217]
如题，可以检查 dollar 和中文有没有空格，英文和中文有没有空格，英文和中文标点符号不能有空格，有没有句号等等。并用颜色标记排版不正确的位置。

这样写题解时，用户可以一键检查排版，避免被打回；管理员可以快速题解审核（不知道会不会用，反正 webadmin 可以考虑一下增加（？））；出题也可以快速检查排版或改别人的排版。

**Comment by YuzhenQin** [comment]
#137
