### ISSUE TITLE
EXLG Dashboard 功能归类、折叠

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#223]
**如果有多个建议，请分别提出，不要扎堆。**

随着挨叉洛谷功能的增多，有必要把它们归类一下了，否则会提高搜索功能的难度。

![K1Y8V RY%H4MBWX60KIO8X](https://user-images.githubusercontent.com/56300237/166124602-0788c03f-8e68-4678-bb34-e0dfb690b68e.png)

如上图，我把犇犇相关的三个功能丢到了一起，原本需要展开的也设置了需要展开，展开后有一个粉色的条。甚至可以这样一直嵌套下去。

如果采用这种方法，搜索会变的容易了很多。

下面是我的一个建议：

- 犇犇 ex
- - 全网犇犇
- - CtrlEnter 发送犇犇
- - 犇犇龙王排行榜
- 博客 ex
- - 题解格式化
- - 博客 Markdown 快捷键
- 题目 ex
- - 双击题号跳题
- - 隐藏题解
- - 随机跳题 ex
- - 题单内随机跳题
- - 创建重现赛
- - 任务计划 ex
- - 返回比赛列表
- 个人主页 ex
- - 用户备注
- - 用户首页 HTML 显示
- - 题目颜色数量和比较
- 讨论 ex
- - 验证码自动填充
- - 讨论保存 
- - 表情输入
- - 有害代码检查器
- - 主页讨论个数限制
- 显示
- - 代码块优化
- - 记录难度可视化
- - 显示原始难度
- - 自定义样式表
- - 标签显示
- - 更新日志显示
- 杂项
- - 键盘操作与命令行
- - 用户查找

这样下来的话我感觉会清晰一些，将所有功能归为了 7 类，在找的时候能够轻松进行一次七选一，然后在每个里面轻松找到。

我上面的示例可能有些不准确，仅供参考，有些功能如果分错了敬请谅解。

**Comment by 5ab-juruo** [comment]
你说的有道理，只不过我觉得分为灌水、学术、显示和技术或许更为合理。

至于实现方式，也许只需要将原有的 5 栏扩充就好了。
