### ISSUE TITLE
翻译更改建议

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#224]
「有害代码检查器」和其英文有些不同，建议改成「恶意代码检查器」。

我没有添加 bug 或 enhancement 的标签，因为这不属于一个故障或者一个功能增强，且没有我需要的模板。

**Comment by YuzhenQin** [comment]
个人认为恶意代码是有害代码的一种，代码作者恶意编写了有害代码。

**Comment by 5ab-juruo** [comment]
写了就不要改了。
