### ISSUE TITLE
添加更多 issue 模板

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#225]
**如果有多个建议，请分别提出，不要扎堆。**

在 #224 中，我没有添加 bug 或 enhancement 的标签，因为这不属于一个故障或者一个功能增强，且没有我需要的模板。

希望添加更多的合适的模板。

**Comment by YuzhenQin** [comment]
暂时没有更多的合适的模板。
