### ISSUE TITLE
使用 TypeScript 重构核心代码

### ISSUE THREAD

**Issue by EarthMessenger** [extend-luogu/extend-luogu#228]
如题（这玩意儿好像不算feature request）

使用 ts 以提供更好的 ide 代码补全支持。

优先重构核心代码，如 core.js, util.js, category.js, comp-core.js 等。同时鼓励新作者使用 ts 编写代码。

**Comment by wxh06** [comment]
我支持，但是有开发者表示怀疑。屎山我也不敢动🤔

**Comment by wxh06** [comment]
WIP
