### ISSUE TITLE
建议增加“主页云剪贴板”功能

### ISSUE THREAD

**Issue by Daijianghao** [extend-luogu/extend-luogu#233]
如题，可以在浴谷主页侧边加上一个云剪贴板。

填写内容可以是收藏的网页、将刷的题单或题目、提醒自己要参加的比赛、或者是奇奇怪怪的东西（比如上面写“你个 fw”或“你今年必须进省队”来激励自己卷题（？））

---

实现方法嘛，只是提供建议我也不懂，可以输入云剪贴板八位地址，然后具体的文字在原剪贴板编辑，然后艺叉洛谷负责把“原云剪贴板”的文字 显示在主页上。

位置嘛，艺叉洛谷 logo 下方好像可以，这比龙王排行榜要有价值的多了，排它上面，当然别的地方也可以。

**Comment by YuzhenQin** [comment]
Use luogu-notepad instead.

**Comment by Daijianghao** [comment]
任务计划的话，只能在主页显示题目，就主页云剪贴板的话可以显示qqgg的网址或一些话语，如题单、团队、收藏的其他文章或其他站外的东西。
这样不用每次note.ms翻了，每次上主页就能提醒自己要刷题单或者激励自己“你个 fw 快去卷题（？）”

**Comment by 5ab-juruo** [comment]
你把洛谷当桌面用了是吧。

**Comment by Daijianghao** [comment]
？增加主页记事本功能不好吗，提醒自己
