### ISSUE TITLE
建议调整命令功能

### ISSUE THREAD

**Issue by Daijianghao** [extend-luogu/extend-luogu#240]
如题，昨天晚上睡觉的时候有的灵感。

参考文献：[int128 的云剪贴板](https://www.luogu.com.cn/paste/vwmiheu1) [github 上的官方帮助文档](https://github.com/extend-luogu/extend-luogu/blob/main/doc/module/keyboard-and-cli.md)

**一、合并 `/cdd,/cc,/go,/uid,/un`（跳转功能）**

因为都是跳转，没必要分那么多，并且难记难分，可以全改为 `/go`。

**1.第一个参数**

按照原 `/cc` 命令，表格。

|主页|题目|比赛|评测记录|讨论|个人中心|私信|通知|用户|
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|`h`|`p`|`c`|`r`|`d`|`i`|`m`|`n`|`u(user)`|

**2.第二个参数**

|第一个参数|第二个参数|建议用法|
|:--:|:--:|:--:|
|`p`|题号|如 `/go p 7866或p7866或P7866` 均跳转至“小昕昕”，建议大小写不敏感，如 `/go p cf1a`|
|`d`|讨论名|如 `/go d ra` 直达灌水区，其他名字英语不好不知道，均按原 `/cdd`|
|`u`|跳转用户|如 `/go 322864` 或 `/go extend-luogu` 均跳转至谔叉洛谷官号|

**3.建议有时第一个参数可省略**

因为跳题算是很常用的功能了吧，洛谷不就是用来刷题的吗。

但是 `go` 在当中，`p` 要移到右上，数字要移到小键盘，就很不方便。

~~而且我右手小指不灵活，`9ol.` 以右的都是无名指控制，包括删除和回车，就右手一直移来移去的很烦~~

建议：`/go 1001=/go p 1001=/go p P1001->跳转 a+b`。

**二、关于 `/cd`**

好像有了 `/go` 的这些功能，`/cd` 好像也没什么用了（？），就是博客可能有点用，留或删好像都行。

（但谁会刻意背网址啊。）

**三、关于 `/help`**

建议询问后，可跳转至官方帮助文档。

真有的时候搞不清 `/cc/ccd/cdd/cd` 分别干什么的。

据不完全统计，问的几个都不知道谔叉洛谷有命令行功能/经常使用命令行，我也是和朋友闲聊时候听别人正好提到，才知道有如此功能强大的东西。

就，如果担心有人用惯了 `/cc/ccd/cdd/cd/un/uid` 这种的话，也可以保留，就增强 `/go` 的功能也行。

**Comment by YuzhenQin** [comment]
#242

**Comment by YuzhenQin** [comment]
Use `Luogu Search AnyWhere` instead.
