### ISSUE TITLE
badge 过长导致显示错误

### ISSUE THREAD

**Issue by ren-yc** [extend-luogu/extend-luogu#244]
## 问题描述

![image](https://user-images.githubusercontent.com/53416099/166643506-b7bfde21-9ef2-4d9b-bdd5-880d4e838d27.png)

可限制 badge 长度来解决此问题。

## 复现

[此贴](https://www.luogu.com.cn/discuss/436155)。

如果方便的话，建议附上截图。

## 环境

Windows 11 22000.652

Microsoft Edge 101.0.1210.32

**Comment by 5ab-juruo** [comment]
首先是，这个链接已经失效了。

但不必再找例子了，马上修。
