### ISSUE TITLE
犇犇排行榜多份bug与babge边框长时间自动消失

### ISSUE THREAD

**Issue by accomplishmentGu** [extend-luogu/extend-luogu#245]
- [x] 问题一、犇犇排行榜多份

## 问题描述
犇犇排行榜在有些情况下会出现40名（可能更多），而且1-20和21-40或更多排行部分相同

## 复现
多次连续点击刷新后，加载完成后，慢慢往下翻，会出现多组犇犇排行榜，与1~20名部分重复

![](https://s3.bmp.ovh/imgs/2022/05/05/dc07164f74c50649.png)

## 环境
Chrome 101.0.4951.54, Windows 10.0.19044.1682 家庭版

- [ ] #321

## 问题描述
设置babge边框后，过一段时间，babge的边框自动消失

## 复现
先在babge注册/修改中设置边框，短时间内边框存在，过一段时间（通常要几个小时），边框自动消失，其他无变化

设置边框后：
![](https://i.bmp.ovh/imgs/2022/05/05/03a23b3a480913d1.png)

过一段时间后：
![](https://i.bmp.ovh/imgs/2022/05/05/4d16a9d9ef03d287.png)

我不清楚我是不是因为自动清空缓存导致的，反正这个问题每天都有

## 环境
Chrome 101.0.4951.54, Windows 10.0.19044.1682 家庭版

**Comment by GuZheran** [comment]
exlg最新版（6.4.2）

**Comment by GuZheran** [comment]
有人接单吗
