### ISSUE TITLE
“我关注的”犇犇无法刷新

### ISSUE THREAD

**Issue by Daijianghao** [extend-luogu/extend-luogu#249]
如题，刷新多次无果。

## 复现

主页->我关注的，无法查看更多犇犇。

## 环境
extend-luogu 6.4.3
Google Chrome 100.0.4896.60（64 位）

**Comment by Daijianghao** [comment]
且无“点击查看更多犇犇”

**Comment by 5ab-juruo** [comment]
6.4.4 没有问题。
