### ISSUE TITLE
badge too long 之后无法正常编辑 badge

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#253]
**如果有多个问题，请分别汇报，不要扎堆。**

## 问题描述
badge too long 之后无法正常编辑 badge，显示请填写 badge。

## 复现
请描述你是怎么遇到这个问题的，尽可能详细以便于管理复现。

先随便改一个超长的 badge，然后会提示 badge too long。
接下来填入 badge，会说请填写 badge。

如果方便的话，建议附上截图。

![image](https://user-images.githubusercontent.com/56300237/167748385-190e0d66-7c18-4c7b-b315-c937d1189734.png)
![image](https://user-images.githubusercontent.com/56300237/167748428-7a73e87b-1f11-4681-b1c9-2197e96f677b.png)
![image](https://user-images.githubusercontent.com/56300237/167748435-384c2eba-e64c-492c-95e7-0d79b83a7926.png)
![image](https://user-images.githubusercontent.com/56300237/167748444-b426d5d9-9319-45d4-b988-afa998719ce7.png)
![image](https://user-images.githubusercontent.com/56300237/167748455-31c4fcf1-bccf-493a-842e-4ec471653111.png)
![image](https://user-images.githubusercontent.com/56300237/167748467-33aff842-b698-4cec-af23-d0615105bf53.png)

## 环境
请描述你使用的浏览器，系统信息，大多时候不是必须的。

exlg 6.4.4
Chrome 101.0.4951.54
Win10 x64

**Comment by YuzhenQin** [comment]
Badge 注册器不再被维护，请查看 extend-luogu/exlg-backend#1。
