### ISSUE TITLE
HTML显示改进

### ISSUE THREAD

**Issue by little-cindy** [extend-luogu/extend-luogu#254]
我感觉现在的显示方式有点bug，例如style无法加载。况且，如果没有装exlg，**就会显示乱码**

所以我觉得最好能加上一个填写HTML的界面，会显示在主页的最前面。

这样，如果没装exlg就不会看到乱码了

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
> 我感觉现在的显示方式有点bug，例如style无法加载。况且，如果没有装exlg，**就会显示乱码**
> 
> 所以我觉得最好能加上一个填写HTML的界面，会显示在主页的最前面。
> 
> 这样，如果没装exlg就不会看到乱码了

有多条建议，分别提出，不要扎堆。

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
> 我感觉现在的显示方式有点bug，例如style无法加载。况且，如果没有装exlg，**就会显示乱码**
> 
> 所以我觉得最好能加上一个填写HTML的界面，会显示在主页的最前面。
> 
> 这样，如果没装exlg就不会看到乱码了

2. 没装 exlg 不会看到乱码的话，你要把 html 放到哪里呢？存到服务器里还是存到你本地只有你自己能看到呢？第二条可能开发者不予实现。

**Comment by little-cindy** [comment]
> > 我感觉现在的显示方式有点bug，例如style无法加载。况且，如果没有装exlg，**就会显示乱码**
> > 所以我觉得最好能加上一个填写HTML的界面，会显示在主页的最前面。
> > 这样，如果没装exlg就不会看到乱码了
> 
> 有多条建议，分别提出，不要扎堆。

你不看内容关我毛事

**Comment by little-cindy** [comment]
> > 我感觉现在的显示方式有点bug，例如style无法加载。况且，如果没有装exlg，**就会显示乱码**
> > 所以我觉得最好能加上一个填写HTML的界面，会显示在主页的最前面。
> > 这样，如果没装exlg就不会看到乱码了
> 
> 2. 没装 exlg 不会看到乱码的话，你要把 html 放到哪里呢？存到服务器里还是存到你本地只有你自己能看到呢？第二条可能开发者不予实现。

存服务器呀

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
> > > 我感觉现在的显示方式有点bug，例如style无法加载。况且，如果没有装exlg，**就会显示乱码**
> > > 所以我觉得最好能加上一个填写HTML的界面，会显示在主页的最前面。
> > > 这样，如果没装exlg就不会看到乱码了
> > 
> > 
> > 
> > 2. 没装 exlg 不会看到乱码的话，你要把 html 放到哪里呢？存到服务器里还是存到你本地只有你自己能看到呢？第二条可能开发者不予实现。
> 
> 存服务器呀

这是 fk 的回答

【管理员】 fk | meta discussion bot | indev 9:00:39
存服务器 -> 成本 -> 付费功能

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
> > > 我感觉现在的显示方式有点bug，例如style无法加载。况且，如果没有装exlg，**就会显示乱码**
> > > 所以我觉得最好能加上一个填写HTML的界面，会显示在主页的最前面。
> > > 这样，如果没装exlg就不会看到乱码了
> > 
> > 
> > 有多条建议，分别提出，不要扎堆。
> 
> 你不看内容关我毛事

然后你的这个东西明显是两条，你为什么不开两个 issues 呢？issue 就是这么用的，你有 20 个就开 20 个。

你的第一个要说的要加 bug 标签，标题为 exlg.html style 无法加载
你的第二个要说的要加 enhancement 标签，标题为 建议 exlg.html 加入云 html 功能，叙述为你现在说的这个

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
> > > 我感觉现在的显示方式有点bug，例如style无法加载。况且，如果没有装exlg，**就会显示乱码**
> > > 所以我觉得最好能加上一个填写HTML的界面，会显示在主页的最前面。
> > > 这样，如果没装exlg就不会看到乱码了
> > 
> > 
> > 
> > 2. 没装 exlg 不会看到乱码的话，你要把 html 放到哪里呢？存到服务器里还是存到你本地只有你自己能看到呢？第二条可能开发者不予实现。
> 
> 存服务器呀

哦对了这个有个新方案 就是后面接云剪贴板八位数

我去新开个 issue

**Comment by wxh06** [comment]
> > 有多条建议，分别提出，不要扎堆。
>
> 然后你的这个东西明显是两条，你为什么不开两个 issues 呢？issue 就是这么用的，你有 20 个就开 20 个。
>
> 你的第一个要说的要加 bug 标签，标题为 exlg.html style 无法加载
> 你的第二个要说的要加 enhancement 标签，标题为 建议 exlg.html 加入云 html 功能，叙述为你现在说的这个

我觉得这个 issue 没有问题，第二个可以视为第一个的解决办法，可以看作一个单一的 feature request。

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
> > > 有多条建议，分别提出，不要扎堆。
> > 
> > 
> > 然后你的这个东西明显是两条，你为什么不开两个 issues 呢？issue 就是这么用的，你有 20 个就开 20 个。
> > 你的第一个要说的要加 bug 标签，标题为 exlg.html style 无法加载
> > 你的第二个要说的要加 enhancement 标签，标题为 建议 exlg.html 加入云 html 功能，叙述为你现在说的这个
> 
> 我觉得这个 issue 没有问题，第二个可以视为第一个的解决办法，可以看作一个单一的 feature request。

第一个不是说 style 无法加载吗，第二个是如何作为第一个的解决办法的

**Comment by wxh06** [comment]
> 第一个不是说 style 无法加载吗，第二个是如何作为第一个的解决办法的

我指的后面内容是“就会显示乱码”解决办法，至于“例如style无法加载”确实可以另外开issue，但是认为前面 `style` 这个问题无关紧要，也是出于安全原因不方便显示。

稍后我会把关于“有多条建议，分别提出，不要扎堆”的讨论折叠掉：视觉上对问题本身的讨论造成不必要的干扰。
以后凡是不是一下子列出数条毫不相关的 bug report 或 feature request 不方便追踪的就不予追究啦。

**Comment by YuzhenQin** [comment]
> 例如style无法加载
```javascript
/** @type {import('xss')} */
export const xss = new filterXSS.FilterXSS({
    onTagAttr: (_, k, v) => {
        if (k === "style") return `${k}="${v}"`;
    },
});
```
