### ISSUE TITLE
exlg.html 加载云剪贴板内的 html

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#255]
**如果有多个建议，请分别提出，不要扎堆。**

在其他人没装 exlg 的时候，用户主页显示的 exlg.html 就是一坨乱码。

建议把要加载的 html 装入云剪贴板，用户可以自行选择是加载云剪贴板里的，或是直接贴源码上去。

建议的格式：Exlg.html> lgpaste-xxxxxxxx

**Comment by wxh06** [comment]
这个 issue 是解决 #254 的实现方法之一。
