### ISSUE TITLE
点击题单，再点“创建者”，仍有“随机跳题”

### ISSUE THREAD

**Issue by Daijianghao** [extend-luogu/extend-luogu#256]
## 复现
比如，点击 [EZEC 的题单](https://www.luogu.com.cn/training/10587)，再点击“创建者”的 EZEC，就会发现 EZEC 出题组的“不可加入”旁边有个“随机跳题”。

[![Orwz0e.png](https://s1.ax1x.com/2022/05/13/Orwz0e.png)](https://imgtu.com/i/Orwz0e)

## 环境
extend-luogu 6.4.4
Google Chrome 100.0.4896.60（64 位）

**Comment by 5ab-juruo** [comment]
洛谷的不刷新加载。

**Comment by YuzhenQin** [comment]
洛谷的不刷新加载。

**Comment by Daijianghao** [comment]
那行吧。
