### ISSUE TITLE
重复显示名字

### ISSUE THREAD

**Issue by tzcawa** [extend-luogu/extend-luogu#261]
对于一个存有犇犇的用户，如果打开他个人主页，还在加载的时候点击 `动态`，就会蹦出来一大堆用户名。

例：![](https://s1.ax1x.com/2022/05/14/OcIolt.png)

Windows 10, Edge, exlg 6.4.4

**Comment by 5ab-juruo** [comment]
在最新版本已修复。

**Comment by tzcawa** [comment]
> 在最新版本已修复。

检查了 10 多遍，当前的 exlg 版本 6.4.4 是最新版本。（？
