### ISSUE TITLE
插件设置为空

### ISSUE THREAD

**Issue by GuZheran** [extend-luogu/extend-luogu#269]
## 问题描述
打开exlg插件设置一片白，什么也没有。

## 复现
点进插件设置，什么也没有。

## 环境
Chrome 101.0.4951.54, Windows 10, exlg 6.5.0

**Comment by FiresonZ** [comment]
win11 edge最新版 exlg 6.6.0 同问题

**Comment by ren-yc** [comment]
![image](https://user-images.githubusercontent.com/53416099/169301992-776142a2-7644-4df9-8039-307e072b1427.png)

补充：控制台报错

**Comment by 5ab-juruo** [comment]
dash.exlg.cc 是远古版本，请使用 extend-luogu.github.io 版本。
