### ISSUE TITLE
干碎挨叉洛谷大图

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#275]
**如果有多个建议，请分别提出，不要扎堆。**

看上去很谔谔 还很大 很狰狞 建议删掉 或者改成一行语气委婉的提醒文字

**Comment by juruo888** [comment]
好像和 #74 duplicate 了（可能太远古了看不到了

**Comment by Primitive-RhodesIsland-Terminal-Service** [comment]
不是重复了 那个是更改 这个是删掉

> 好像和 #74 duplicate 了（可能太远古了看不到了
