### ISSUE TITLE
badge 纯净模式

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#276]
**如果有多个建议，请分别提出，不要扎堆。**

Luogu @[AlgorithmerSnow](https://www.luogu.com.cn/user/419487) 2022-05-20 12:40：恶心的还有一群弱智 badge。能不能帮我反馈一下开一个 badge 纯净模式，就是本机显示全部变成原来的淡蓝色，跟形形色色的广告摊位似的

in https://www.luogu.com.cn/discuss/440786?page=2

**Comment by 5ab-juruo** [comment]
不爽可以把 badge 关掉啊，真的要改也就一行 css 的事，咋这都不愿意呢。
