### ISSUE TITLE
dash 模块设置显示优化建议

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#279]
**如果有多个建议，请分别提出，不要扎堆。**

当转到某个模块的详细设置时，建议将此模块颜色加深变灰一点。

![image](https://user-images.githubusercontent.com/56300237/169499585-d72ebba5-c27c-4133-b44c-d21323bdb6f3.png)

现在只有鼠标悬浮在上面会这个效果。建议进入设置页面，对应模块的变灰比这个浅一点。

**Comment by 5ab-juruo** [comment]
没有必要。
