### ISSUE TITLE
对元讨论引导的建议

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#280]
**如果有多个建议，请分别提出，不要扎堆。**

1. 把元讨论引导变成无法关闭。
2. 增加判定关键词，如「挨叉洛谷」「扩展洛谷」「恶心洛谷」「extend-luogu」等。

现在有了元讨论引导但是依旧存在占用讨论现象。最近见到的一个 exlg 求助帖是没写 exlg 的，写了「扩展洛谷」。

**Comment by ForkKILLET** [comment]
之前权衡得出的结论是没有必要，关键字可以安排但恐怕不会有什么效果。

你说的那个帖子应该是他 exlg 炸了所以没弹框。

不会有什么效果的原因：弹框只是一个共情 + 声明，完全禁止只会让某些用户产生逆反心理。而且要绕过引导只需要短暂关闭 exlg 就行了……
