### ISSUE TITLE
题单随机跳题检测问题（疑似操作失误）

### ISSUE THREAD

**Issue by ForkKILLET** [extend-luogu/extend-luogu#282]
_from [meta discussion p37](https://www.luogu.com.cn/discuss/432028?page=37), by @[李嘉欢](https://www.luogu.com.cn/user/528472)_

## 复现

未知
截图 
![图片](https://user-images.githubusercontent.com/35412022/169502771-da72fb07-e87c-4006-b49a-eb8a9ae66b94.png)

## 环境

未知

**Comment by ForkKILLET** [comment]
疑似使用方法有误……

**Comment by juruo888** [comment]
请在标题简单描述你的问题
