### ISSUE TITLE
被删讨论自动跳转

### ISSUE THREAD

**Issue by ioi-ak-dajuruo888** [extend-luogu/extend-luogu#285]
就是打开一个讨论，如果被删除了，就跳转到 luogulo 的对应页面

**Comment by juruo888** [comment]
> 比较难实现（指每页同步浏览进度）

我觉得打开一个讨论时判断是否被删，若被删则获取 url，然后跳转到 `https://xn--fx-ex2c330n.ml/show.php?url=`+讨论的 url

**Comment by juruo888** [comment]
> > > 比较难实现（指每页同步浏览进度）
> > 
> > 
> > 我觉得打开一个讨论时判断是否被删，若被删则获取 url，然后跳转到 `https://xn--fx-ex2c330n.ml/show.php?url=`+讨论的 url
> 
> 但是 lg 不会返回删掉的帖子啊

好像会返回 403 还是什么，可以 F12 看看

也可以查询页面有没有 `不存在的讨论`
