### ISSUE TITLE
colorpicker 无法加载

### ISSUE THREAD

**Issue by EarthMessenger** [extend-luogu/extend-luogu#287]
**如果有多个问题，请分别汇报，不要扎堆。**

## 问题描述

colorpicker 无法加载

## 复现

由于 gitee 的政策，https://gitee.com/xiannvzuo/xncolorpicker/raw/main/dist/xncolorpicker.min.js 无法加载，在 violentmonkey 环境下会导致脚本无法安装。

![image](https://user-images.githubusercontent.com/49364506/169555973-65c5c15a-f1a8-4783-97f4-d00af3fa2a88.png)

```bash
[emsger@emsger ~]$ curl 'https://gitee.com/xiannvzuo/xncolorpicker/raw/main/dist/xncolorpicker.min.js' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0'
[session-3249b4b4] Route error: The Repository is invisible. see: https://gitee.com/xiannvzuo/xncolorpicker
```

虽然我到现在也不知道这个 colorpicker 到底干啥的。

## 环境

firefox developer edition 101.0b8
violentmonkey 2.13.0

**Comment by 5ab-juruo** [comment]
正在考虑更换 colorpicker，这个东西因为 eval 已经整出不少问题了。
