### ISSUE TITLE
私信界面新消息提示

### ISSUE THREAD

**Issue by Primitive-RhodesIsland-Terminal-Service** [extend-luogu/extend-luogu#288]
**如果有多个问题，请分别汇报，不要扎堆。**

## 问题描述

我在私信界面也能收到新消息提示，难道不是多此一举吗（）

## 复现

![image](https://user-images.githubusercontent.com/56300237/169627730-66cf4aba-4d6e-4d03-9804-6235b4852fc9.png)

如果方便的话，建议附上截图。

## 环境

exlg 6.6.0

**Comment by juruo888** [comment]
这不是 bug 吧（

**Comment by YuzhenQin** [comment]
在新的消息提醒模块中已经修复。
