### ISSUE TITLE
表情源挂了

### ISSUE THREAD

**Issue by EarthMessenger** [extend-luogu/extend-luogu#293]
## 问题描述

表情源挂了

具体是 **妙.tk** 和 **jsdelivr**。

### 妙.tk

应该是域名挂了。

![图片](https://user-images.githubusercontent.com/49364506/169649096-770e6815-f87d-4f98-b35f-ac3ccf2ea5f8.png)

### jsdelivr

dns 污染了，这个我们肯定修不好。

jsdelivr/jsdelivr#18397

![图片](https://user-images.githubusercontent.com/49364506/169648972-ae525578-1250-4d47-a5e0-04690c23069d.png)

## 环境

中国移动
dns: 阿里云公共DNS

**Comment by 5ab-juruo** [comment]
明白了，下个版本就 ban 掉这两个源

**Comment by 5ab-juruo** [comment]
fixed since 8cf2cf7e5d0ddb0759a87e585600a9d1dd74a010
