### ISSUE TITLE
主页上方同时出现六个exlg控制桥

### ISSUE THREAD

**Issue by KaiserWilheim** [extend-luogu/extend-luogu#297]
## 复现

![image.png](https://s2.loli.net/2022/05/22/LJniYAlNhagS41U.png)

复现过程：
1. 在控制面板内关闭控制桥
2. 刷新洛谷主页，此时主页上方没有控制桥
3. 关闭exlg油猴插件，并刷新洛谷主页
4. 再次打开exlg油猴插件并刷新洛谷主页
5. 在通过连接调出的控制面板中打开控制桥
6. 刷新洛谷主页，上方出现六个控制桥

重启浏览器之后就无法复现。

## 环境

Chrome浏览器，100.0.4896.75（64位）
exlg版本5.8.2
同时挂载的油猴插件有Luogu Search Anywhere。

虽说是老版本了，但是碰巧遇到了，就汇报一下。

**Comment by wxh06** [comment]
> @YuzhenQin
> exlg5都eol了
