### ISSUE TITLE
无法修改badge

### ISSUE THREAD

**Issue by iudwgerte** [extend-luogu/extend-luogu#301]
## 问题描述
在洛谷首页无法修改badge
## 复现
在洛谷首页点击`修改/注册 badge`
## 环境
- extend-luogu 6.7.0

**Comment by luogu557680** [comment]
更新为 [6.7.3-pre2](https://github.com/extend-luogu/extend-luogu/releases/download/6.7.3-pre2/extend-luogu.min.user.js) 试试
