### ISSUE TITLE
无法修改Badge

### ISSUE THREAD

**Issue by CNLanS** [extend-luogu/extend-luogu#302]
## 问题描述
无论在洛谷的哪个页面，都无法打开最新版exlg的badge注册或修改页面

## 复现
在洛谷任意界面尝试打开exlg的badge修改/注册界面

## 您预期的行为

badge界面打开

## 实际运行的效果

![image](https://user-images.githubusercontent.com/102409834/170723134-913cc925-95be-475b-9a19-68d6ef13789e.png)

## 环境

Microsoft Edge & Exlg 6.7.1

**Comment by luogu557680** [comment]
更新为 [6.7.3-pre2](https://github.com/extend-luogu/extend-luogu/releases/download/6.7.3-pre2/extend-luogu.min.user.js) 试试
