### ISSUE TITLE
建议添加批量删私信功能

### ISSUE THREAD

**Issue by xkh01** [extend-luogu/extend-luogu#304]
建议出一个批量删除私信的功能，手删太麻烦了

**Comment by xkh01** [comment]
> 是否有必要？删了别人也看得见

对于有的人来说有用吧，比如我，昨天删私信删到手软还没删完……

**Comment by wxh06** [comment]
我不认为有必要，但可以进一步讨论

Feel free to reopen this issue

**Comment by wxh06** [comment]
PRs are welcome
