### ISSUE TITLE
论 exlg 的 badge 可以嵌入 html

### ISSUE THREAD

**Issue by OIer1048576** [extend-luogu/extend-luogu#311]
## badge 可以嵌入 html
我发现 badge 现在可以嵌入 html，这里有 xss 风险（虽然有badge长度限制，但是如果限制被用户/脚本编辑，会造成后果）。
![AHMPERQ2ID`JII H2)ZT$F1](https://user-images.githubusercontent.com/86519105/173176346-0e4833cc-b9e8-4af4-8c94-a89a117e91af.png)
这里是 badge嵌入换行符。

**Comment by wxh06** [comment]
uid 多少？

**Comment by wxh06** [comment]
> uid 多少？

360265，根据用户名找到了

**Comment by wxh06** [comment]
复现了，修改后在缓存期限内仅自己可见

（），你们就偷着乐吧

**Comment by YuzhenQin** [comment]
#321
