### ISSUE TITLE
建议修改保存讨论的网站

### ISSUE THREAD

**Issue by luogu557680** [extend-luogu/extend-luogu#313]
[luogulo.gq](https://luogulo.gq) 现在不能用来保存帖子了，只能用 [fx白丝.ml](https://fx白丝.ml) 保存帖子，建议将 [luogulo.gq](https://luogulo.gq) 改为  [fx白丝.ml](https://fx白丝.ml)，谢谢。

**Comment by wxh06** [comment]
![兔队在QQ群的发言](https://user-images.githubusercontent.com/29367025/173346056-0a403604-3528-4b6c-acaf-2b76164026fb.png)

**Comment by 5ab-juruo** [comment]
只要给我们打钱，我们就立刻换一个域名。

**Comment by YuzhenQin** [comment]
已经购买了 [https://lglg.top](https://lglg.top)
