### ISSUE TITLE
建议取消脚本的压缩

### ISSUE THREAD

**Issue by EarthMessenger** [extend-luogu/extend-luogu#314]
建议取消脚本的压缩。

压缩后脚本的变量名被破坏，控制台中显示的堆栈报错几乎不可读，让用户反馈控制台信息意义不大。并且用户脚本的大小不会明显地影响加载速度，压缩没有意义（除了可以省点 oss 流量）。

**Comment by undefined-moe** [comment]
小知识：使用 sourcemap 是可以还原堆栈信息的

**Comment by wxh06** [comment]
> 小知识：使用 sourcemap 是可以还原堆栈信息的
