### ISSUE TITLE
四个建议：自定义快捷链接、搜索题号跳转、题库随机跳转、题目笔记和标签

### ISSUE THREAD

**Issue by SteveTaizhou** [extend-luogu/extend-luogu#316]
1. 加入自定义快捷链接的功能
2. 右上角的搜索框按下Enter后，如果是题号那自动跳转题目，不用再跳转到题库页面
3. 题库页面加入随机跳转功能
4. 题目加入笔记和标签功能

**Comment by SteveTaizhou** [comment]
就像这个：

![Snipaste_2022-06-19_13-35-41](https://user-images.githubusercontent.com/85382878/174467422-f9e9de77-d852-446c-bd59-f7e407c69894.png)

**Comment by SteveTaizhou** [comment]
建议2的意思是：

![Snipaste_2022-06-19_13-42-10](https://user-images.githubusercontent.com/85382878/174467565-5cf8a7de-5ee5-47b5-873f-b1221f42add3.png)

**Comment by SteveTaizhou** [comment]
建议1可参考《洛谷首页置顶助手》。附源码：<https://gist.github.com/SteveTaizhou/5561c103c576e8dbb33d270c9e6babd4>

**Comment by SteveTaizhou** [comment]
建议4：

每一道题对应一个笔记，应当支持MarkDown，作为思路的临时保存站。个人使用，不公开。
每一题就好像用户备注一样，可以设置题目标签，显示在题目旁边。可以在题库页面的题目旁边或者弹出标签显示标记内容。

笔记（没写代码）：

![Snipaste_2022-06-19_14-53-11](https://user-images.githubusercontent.com/85382878/174469638-2596baf0-0bb8-4b6a-950f-684c1fe6616f.png)

标签（没写代码）：

![Snipaste_2022-06-19_14-59-26](https://user-images.githubusercontent.com/85382878/174469696-636811f3-e3eb-4b01-94b5-3f8e7a9bd4e4.png)

**Comment by wxh06** [comment]
**如果有多个建议，请分别提出，不要扎堆！以方便我们追踪实现的进度**

**Comment by SteveTaizhou** [comment]
ok

**Comment by wxh06** [comment]
谢谢，那这个 issue 这边先 close 啦

**Comment by SteveTaizhou** [comment]
好的
