### ISSUE TITLE
建议：搜索题号跳转

### ISSUE THREAD

**Issue by SteveTaizhou** [extend-luogu/extend-luogu#318]
### 介绍

右上角的搜索框按下Enter后，如果是题号那自动跳转题目，不用再跳转到题库页面

### 模拟

意思是：

![Snipaste_2022-06-19_13-47-30](https://user-images.githubusercontent.com/85382878/174467661-7f15d158-d2ff-4b29-80cf-0b690852635c.png)

**Comment by YuzhenQin** [comment]
Use Luogu Search AnyWhere instead.
