### ISSUE TITLE
建议：题库随机跳转

### ISSUE THREAD

**Issue by SteveTaizhou** [extend-luogu/extend-luogu#319]
### 概述

题库页面加入随机跳转功能

### 模拟

就像这个（题库底部）：

![Snipaste_2022-06-19_13-35-41](https://user-images.githubusercontent.com/85382878/174467422-f9e9de77-d852-446c-bd59-f7e407c69894.png)

我干的是（代码没写）：

![Snipaste_2022-06-19_13-37-31](https://user-images.githubusercontent.com/85382878/174467455-45c34319-d19c-41be-99e7-701fa4bec782.png)

**Comment by YuzhenQin** [comment]
您可以尝试一下 contribute？
