### ISSUE TITLE
建议：题目笔记和标签

### ISSUE THREAD

**Issue by SteveTaizhou** [extend-luogu/extend-luogu#320]
### 概述

题目加入笔记和标签功能

### 介绍

每一道题对应一个笔记，应当支持MarkDown，作为思路的临时保存站。个人使用，不公开。
每一题就好像用户备注一样，可以设置题目标签，显示在题目旁边。可以在题库页面的题目旁边或者弹出标签显示标记内容。

### 模拟

笔记（没写代码）：

![Snipaste_2022-06-19_14-53-11](https://user-images.githubusercontent.com/85382878/174469638-2596baf0-0bb8-4b6a-950f-684c1fe6616f.png)

标签（没写代码）：

![Snipaste_2022-06-19_14-59-26](https://user-images.githubusercontent.com/85382878/174469696-636811f3-e3eb-4b01-94b5-3f8e7a9bd4e4.png)

![Snipaste_2022-06-19_15-05-03](https://user-images.githubusercontent.com/85382878/174469825-ff0aeb84-80d3-4f51-a4ce-25f0d61e83df.png)

**Comment by YuzhenQin** [comment]
Duplicate issue #238
