### ISSUE TITLE
卷王监视器工作不正常

### ISSUE THREAD

**Issue by juruo888** [extend-luogu/extend-luogu#324]
## 复现

打开 Exlg 和洛谷，打卡。

## 您预期的行为

弹出卷王监视器的卷王情况。

## 实际运行的效果

啥也没做。

## 环境

Edge 103.0.1264.37

Tampermonkey v4.16.1

Exlg 6.7.4

Luogu 4 Ver 20220624

**Comment by 5ab-juruo** [comment]
我已经修好了，但是由于开发组在搞事情所以还没 push。请耐心等待。

**Comment by 5ab-juruo** [comment]
fixed since 37fade36daeb9cb2b782b82ad766c5328f330b37
