### ISSUE TITLE
建议：增加样例字体优化功能

### ISSUE THREAD

**Issue by Daijianghao** [extend-luogu/extend-luogu#325]
如题，罗马体用于样例，真的觉得，太丑了。

Typewriter，Fira Code 比它好看多了。

可在控制面板中增加“样例优化”，如同“代码块优化”。

**Comment by YuzhenQin** [comment]
请自行了解使用自定义 CSS。

另：exlg近期bug频发，我们正在着手解决这些问题；为了给大家提供更多更棒的功能，我们决定进行一次大规模重构，在此期间不会发布内容更新。













在 2022-06-30 09:08:59，"Huxin" ***@***.***> 写道：

如题，罗马体用于样例，真的觉得，太丑了。

Typewritter，Fira Code 比它好看多了。

可在控制面板中增加“样例优化”，如同“代码块优化”。
