### ISSUE TITLE
随机跳题六重奏

### ISSUE THREAD

**Issue by SteveTaizhou** [extend-luogu/extend-luogu#326]
## 复现

先打开题单，没有按钮，刷新之后就有六个按钮了。

![Snipaste_2022-07-03_09-32-56](https://user-images.githubusercontent.com/85382878/177020997-2bd53b68-fee2-4208-b9b3-7dd252f82571.png)

## 环境

1. ![Snipaste_2022-07-03_09-30-16](https://user-images.githubusercontent.com/85382878/177020942-216f141c-7f90-416d-9640-cb6b54df6f8d.png)

2. ![Snipaste_2022-07-03_09-30-58](https://user-images.githubusercontent.com/85382878/177020964-e500a596-d688-4ed4-a284-42618180a5ce.png)

猜测和<https://github.com/extend-luogu/extend-luogu/issues/168>是一个毛病

**Comment by juruo888** [comment]
是否安装 LuoguSearchAnyWhere？

**Comment by juruo888** [comment]
若安装请将 LuoguSearchAnyWhere 和 Exlg 更新到最新版本
