### ISSUE TITLE
rmj 的“原始难度” 会因为"推荐题目"而显示错误

### ISSUE THREAD

**Issue by OIer1048576** [extend-luogu/extend-luogu#330]
一不小心手滑按了个enter。
## 效果
![image](https://user-images.githubusercontent.com/86519105/178165894-9fa1c9a9-eea4-401a-8d2f-85f5f98bb7d3.png)
效果如图

## 复现
打开任意一道 remotejudge 题目，在下方的推荐题目中任意选择，原始难度将不会变动。

## 系统环境
- Win10
- MsEdge
- Exlg 6.7.4
- Argon Luogu(Script ver)
- LuoguSearchAnywhere

**Comment by 5ab-juruo** [comment]
_feInjection 害人不浅。
