### ISSUE TITLE
[Bug Report] 主页犇犇的表情不加载

### ISSUE THREAD

**Issue by juruo888** [extend-luogu/extend-luogu#333]
打开主页时，犇犇上方并没有出现表情输入。

**Comment by ren-yc** [comment]
`图.tk` 炸了，请更换犇犇表情源。

**Comment by ForkKILLET** [comment]
没炸啊……？![](//图.tk/r)

**Comment by juruo888** [comment]
使用新版 Exlg 并未加载，在 Dashboard 查看显示并未加载

![image](https://user-images.githubusercontent.com/106530969/178931252-2c20f937-0140-4521-96dd-c6589bb89dcb.png)

**Comment by juruo888** [comment]
询问同学后确认新版 Exlg 不会加载犇犇表情
