### ISSUE TITLE
badge注册器格式问题

### ISSUE THREAD

**Issue by little-cindy** [extend-luogu/extend-luogu#334]
## 环境
- 分辨率：1920*1080
- 系统：Ubuntu 20.04.4 LTS
- 操作系统：64位
- 电脑：ThinkPad-E15
- 浏览器：火狐浏览器
## 问题
badge注册器格式出错
## 截图
![](https://cdn.luogu.com.cn/upload/image_hosting/6zx62lg8.png)

**Comment by little-cindy** [comment]
图片貌似挂了，链接：<https://cdn.luogu.com.cn/upload/image_hosting/6zx62lg8.png>

**Comment by ren-yc** [comment]
这个老 Bug 了吧 😓

**Comment by YuzhenQin** [comment]
已修复。

**Comment by YuzhenQin** [comment]
已修复。
