### ISSUE TITLE
Extend Luogu插件设置界面无内容

### ISSUE THREAD

**Issue by cyrxdzj** [extend-luogu/extend-luogu#336]
如图。
![image](https://user-images.githubusercontent.com/63708985/179958151-ef070c8d-dd85-49d8-a448-9e76f1c5ec56.png)
![image](https://user-images.githubusercontent.com/63708985/179958190-861461a1-7321-4140-be15-f4d3a5ca107f.png)
无论是 https://dash.exlg.cc/ 还是 https://extend-luogu.github.io/exlg-setting-new/ 都有这个问题。

**Comment by cyrxdzj** [comment]
操作系统：Windows 11 Version 21H2 (Build 22000.795)
浏览器：Microsoft Edge 103.0.1264.62 (正式版本) (64 位)

**Comment by 5ab-juruo** [comment]
好了吗，还是依旧有问题。

**Comment by cyrxdzj** [comment]
> 好了吗，还是依旧有问题。

还是有问题。

**Comment by cyrxdzj** [comment]
@YuzhenQin 这个问题并未被修复。
