### ISSUE TITLE
注册badge页面显示已激活，但是注册是显示invalid activation 注册失败

### ISSUE THREAD

**Issue by yxr-yolanda** [extend-luogu/extend-luogu#337]
![image](https://user-images.githubusercontent.com/87292018/179990798-f6bbab7f-73d0-42ad-b86e-8ab6ed805462.png)

**Comment by immccn123** [comment]
同问

**Comment by ren-yc** [comment]
#334

**Comment by l-fog** [comment]
Cu ball

**Comment by 5ab-juruo** [comment]
> 同问
> 
> 看了下网络，似乎注册的时候没有发请求
> 
> 浏览器信息	
> Microsoft Edge	103.0.1264.62 (Official build) (64-bit)
> Revision	e5d152f334ae94abb94393154b2e6dbc8961160f
> Operating system	Windows 11 Version 21H2 (Build 22000.795)
> JavaScript	V8 10.3.6.9
> User agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)

使用 Tampermonkey api 看不到请求的。

**Comment by LuoShaoyin** [comment]
What's More : 

Unable to activate badge on [official page](https://exlg.cc/donate.html) .

**Comment by LuoShaoyin** [comment]
What's More : 

Unable to activate badge on [official page](https://exlg.cc/donate.html) .  

ERROR LOG: "backend outdated, please update exlg!" 
ENVIRONMENT: 
  System: Ubuntu 22.04, 5.15.0-43-generic, gnome 4,42 on wayland
  Browser:  chrome ( Version 103.0.5060.134 (Official Build) (64-bit) )

**Comment by 5ab-juruo** [comment]
> What's More :
> 
> Unable to activate badge on [official page](https://exlg.cc/donate.html) .
> 
> ERROR LOG: "backend outdated, please update exlg!" ENVIRONMENT: System: Ubuntu 22.04, 5.15.0-43-generic, gnome 4,42 on wayland Browser: chrome ( Version 103.0.5060.134 (Official Build) (64-bit) )

官网早寄了。

**Comment by 5ab-juruo** [comment]
现在注册器写的就是狗屎，我们马上糊一个注册脚本先凑合着用。
