### ISSUE TITLE
下载模块后无法切换面板

### ISSUE THREAD

**Issue by sunzhangchang** [extend-luogu/extend-luogu#343]
使用Tampermonkey。

市场中下载模块后点切换面板（模块，开发选项），上面变了，但是下面还是显示市场的内容。
点exlg-celeste按钮无法收起面板。
刷新网页后可以跳转。

**Comment by 5ab-juruo** [comment]
疑似 vue bug。

**Comment by YuzhenQin** [comment]
无法复现
