### ISSUE TITLE
标签BUG和备份BUG

### ISSUE THREAD

**Issue by Macesuted012** [extend-luogu/extend-luogu#345]
1.标签未知原因会错位

![image](https://user-images.githubusercontent.com/98137829/181904661-d7b82eb4-be68-45cf-8557-8f12eb77e491.png)

2.讨论贴备份因 fx白丝.ml 更换到 lglg.top 导致失效

**Comment by 5ab-juruo** [comment]
1. 期望行为。
2. 马上修。

**Comment by Macesuted012** [comment]
> 1. 期望行为。
> 2. 马上修。

大佬，您确实把 fx白丝.ml 换成了 lglg.top , 但是您在 6.7.6 版本中没有 //@connect lglg.top 导致还是不能用
