### ISSUE TITLE
一个较为严重的 bug

### ISSUE THREAD

**Issue by xkh01** [extend-luogu/extend-luogu#351]
## 情况

在启用 exlg 后，如果在题目详情页面点击左边的题库按钮，网页上方的进度条会无限循环（但并不会顶到头），10 秒后则会提示超时，使用右上角的搜题也是一样。

但是如果使用命令行来跳转将不会出现上述情况。

## 控制台

（在不断弹这个报错，进度条循环一次弹一次）
<img width="530" alt="image" src="https://user-images.githubusercontent.com/66284192/185267428-19bb79df-c7f6-47af-9184-0c00c7311c82.png">

## 环境

macOS 12.1，Chrome 104.0.5112.101，exlg 6.7.6

**Comment by YuzhenQin** [comment]
是否能提供 log

**Comment by xkh01** [comment]
> 

修改了

**Comment by xkh01** [comment]
> 是否能提供 log，以及 exlg 版本（legacy/celeste）

修改了
