### ISSUE TITLE
在题单中出现多个随机跳题按钮

### ISSUE THREAD

**Issue by ACnoway** [extend-luogu/extend-luogu#360]
在用户分享的题单中100%出现，在官方题单中大概率出现

[![xlDzBn.png](https://s1.ax1x.com/2022/10/05/xlDzBn.png)](https://imgse.com/i/xlDzBn)

[![xlDxns.png](https://s1.ax1x.com/2022/10/05/xlDxns.png)](https://imgse.com/i/xlDxns)

**Comment by 66Leo66** [comment]
#350 可能与你的问题类似？你有没有安装Luogu Search Anywhere脚本

**Comment by ACnoway** [comment]
> #350 可能与你的问题类似？你有没有安装Luogu Search Anywhere脚本

装了，把lsaw关了就没事了，两个都是最新版本，估计是兼容性的问题
