### ISSUE TITLE
适配 Luogu 新更新（AtCoder 题号的更改，练习情况主页的更改）

### ISSUE THREAD

**Issue by APJifengc** [extend-luogu/extend-luogu#361]
- [x]  双击题号跳题不支持改版后的 AtCoder 题号。

- [ ] 题目颜色数量和比较无法适配新的练习情况界面。

![image](https://user-images.githubusercontent.com/55266764/197971001-df73b6c1-434c-487d-af23-87734d04f5bf.png)

**Comment by HelloOSMe** [comment]
Cu

**Comment by Leaf-Coder** [comment]
![image](https://github.com/extend-luogu/extend-luogu/assets/86403408/57d0dba8-6632-4267-bf71-e1a705474b67)
提供个不知道有没有用的信息，提交记录也会出现相似的问题

（要是真都是蓝题那可太好了（雾））
