### ISSUE TITLE
题目颜色不准确且有时无法显示

### ISSUE THREAD

**Issue by Alex-Github-Programmer** [extend-luogu/extend-luogu#362]
截自 小粉兔 的练习：

![](https://cdn.luogu.com.cn/upload/image_hosting/libvutyt.png)

可以看到有的黑题甚至被标成了红题。（我猜测可能和之前的一些恶评有关。）同时，只有 尝试过的题目 和黑题被上色；且刷新以后全部没有被上色。

使用的浏览器及系统：

项目 | 值
-- | --
Microsoft Edge | 108.0.1462.46 (正式版本) (64 位)
操作系统 | Windows 10 Version 21H1 (Build 19043.928)
JavaScript | V8 10.8.8.10
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.46

**Comment by eventlOwOp** [comment]
啊现在不是不上色了吗?

**Comment by eventlOwOp** [comment]
解决措施应该是删除染色插件

**Comment by YuzhenQin** [comment]
Merged into #361.
