### ISSUE TITLE
对于Safari浏览器的支持

### ISSUE THREAD

**Issue by CLCK0622** [extend-luogu/extend-luogu#366]
如题，想问未来是否可能或有计划支持Safari浏览器的EXLG使用？
感谢🙏

**Comment by mcoi-dev** [comment]
额有没有一种可能是要油猴支持了插件才能支持，如果要Issue是否可以发到油猴里？

**Comment by CLCK0622** [comment]
> 额有没有一种可能是要油猴支持了插件才能支持，如果要Issue是否可以发到油猴里？

啊这样吗 谢谢了 我之前不是很清楚 因为我看safari装了油猴再加载exlg能加载成功但是没反应 所以以为是你们这边的问题 不好意思 😢

**Comment by YuzhenQin** [comment]
> 如题，想问未来是否可能或有计划支持Safari浏览器的EXLG使用？ 感谢🙏

你好，

Tampermonkey for mac Safari 仅能支持 userscript 功能，部分 Tampermonkey/油猴 接口并未提供，因此不能使用 exlg。
