### ISSUE TITLE
lglg.top 好像用不了 | dash.exlg.cc证书过期

### ISSUE THREAD

**Issue by Find-NICK** [extend-luogu/extend-luogu#368]
![image](https://user-images.githubusercontent.com/116571277/215479732-05f4384b-b2ae-47bc-91cc-13fc4d5aff07.png)

![image](https://user-images.githubusercontent.com/116571277/215480338-c65e982e-2b93-45be-b771-b91dbb4bc268.png)

操作系统:Windows 10

浏览器:Chrome 109.0.5414.120（64 位）

**Comment by YuzhenQin** [comment]
你好，

dash.exlg.cc 已经不再使用。

lglg.top 尚未部署完成，但该服务器可以 ping 到。请检查您的网络环境。

如果您有其他疑问，请重新打开此 issue。
