### ISSUE TITLE
exlg验证码自动填充无法识别大小写

### ISSUE THREAD

**Issue by g1thubhack3r** [extend-luogu/extend-luogu#374]
如题。  
证据：
<img width="153" alt="屏幕截图 2023-06-29 205801" src="https://github.com/extend-luogu/extend-luogu/assets/125267748/5b7b0c49-8c1c-4645-8585-a3441ad7d0ae">
<img width="164" alt="屏幕截图 2023-06-29 205907" src="https://github.com/extend-luogu/extend-luogu/assets/125267748/703798bb-d308-454e-9d32-578b0d275b77">
<img width="153" alt="屏幕截图 2023-06-29 205922" src="https://github.com/extend-luogu/extend-luogu/assets/125267748/15fdb860-908f-41d1-a5ee-ee5b75594fb4">

**Comment by ren-yc** [comment]
你家验证码大小写敏感？

**Comment by g1thubhack3r** [comment]
对，显示验证码不对，让从新填

**Comment by g1thubhack3r** [comment]
现在测试好像不区分了

**Comment by g1thubhack3r** [comment]
对不起各位，我没看清就来发issue了
