### ISSUE TITLE
Bug:洛谷讨论区自动验证码

### ISSUE THREAD

**Issue by TengMax** [extend-luogu/extend-luogu#380]
## 复现

洛谷讨论区进行了更新：
![image](https://github.com/extend-luogu/extend-luogu/assets/126469376/33943724-09c3-4e2f-85fd-4e8027c5d879)
然后回复讨论时没有自动填充验证码了（我懒）
不知道是不是浏览器的问题
也许这不算Bug
![image](https://github.com/extend-luogu/extend-luogu/assets/126469376/cb0f4f4d-ece3-4208-8fdf-1c89d273a602)

## 您预期的行为
像之前一样，自动填充验证码

## 环境

Microsoft Edge
版本 116.0.1938.69 (正式版本) (64 位)

**Comment by optimize-2** [comment]
fixed.
