### ISSUE TITLE
dashboard (控制面板/设置/dash.exlg.cc) 无法访问

### ISSUE THREAD

**Issue by Huasushis** [extend-luogu/extend-luogu#393]
## 复现

从 github 安装预览版本，版本号：6.7.8。进入洛谷任意页面，点击头像旁 exlg 的图标，跳转到 [https://dash.exlg.cc/index.html](https://dash.exlg.cc/index.html)，浏览器显示连接超时。经过测试，无论是否挂代理都不行。

## 您预期的行为

显示设置界面。

## 实际运行的效果

连接超时。

## 环境

浏览器：Mozilla Firefox Snap for Ubuntu 119.0.1 (64 位) 。

油猴插件：Tampermonkey 4.19.0

**Comment by YuzhenQin** [comment]
exlg 非 celeste 的版本已不再维护。
