### ISSUE TITLE
“传送至cph”按钮显示异常

### ISSUE THREAD

**Issue by xiaofu-15191** [extend-luogu/extend-luogu#396]
## 复现

进入题目/任意比赛界面，正常出现“传送至cph”按钮，直接点击跳转到其他不应显示的界面（如讨论区）仍会出现。

![](https://github.com/xiaofu-15191/blog-img/blob/main/exlg_bug.gif?raw=true)

## 您预期的行为

exlg不在讨论等截面显示"传送至cph"

## 实际运行的效果

exlg在讨论等界面显示"传送至cph"

## 环境

Edge 121.0.2277.83，tampermonkey v5.0.6192，exlg v6.7.8

**Comment by YuzhenQin** [comment]
exlg 非 celeste 的版本已不再维护。
