### ISSUE TITLE
【BUG】题目颜色极其错乱

### ISSUE THREAD

**Issue by CodingCow1** [extend-luogu/extend-luogu#400]
## 问题描述

打开洛谷个人中心的练习页面就会发现，exlg 的题目颜色非常不对，就像这样：

![image](https://github.com/extend-luogu/extend-luogu/assets/161002820/7ce08519-d135-49fc-975e-21d6577dcadd)

## 可能的解决方法

并不清楚 exlg 具体实现的方法，如果是基于数据库索引的，那么可能更新一下数据库可以解决问题。

---

希望早日能解决，要不然练习页面看起来真的很五彩斑斓。

**Comment by YuzhenQin** [comment]
这是由于洛谷已经引入相关功能。请直接关闭该模块。该模块将不再维护。
