### ISSUE TITLE
图.tk崩了

### ISSUE THREAD

**Issue by JiarongGuo** [extend-luogu/extend-luogu#401]
## 复现

表情发不上去：![](https://cdn.luogu.com.cn/upload/image_hosting/uqdelkdn.png)
直接访问不了 ：![](https://cdn.luogu.com.cn/upload/image_hosting/irl0hik0.png)
## 实际运行的效果

我觉得这两个不必多说。
## 环境

浏览器：Microsoft Edge
版本 126.0.2592.53 (正式版本) beta (64 位)
系统：Windows 11 23H2
build 22635.3566（注意，WIP Beta版本！）

**Comment by JiarongGuo** [comment]
![](https://cdn.luogu.com.cn/upload/image_hosting/irl0hik0.png)
![](https://cdn.luogu.com.cn/upload/image_hosting/uqdelkdn.png)

**Comment by JiarongGuo** [comment]
图片 1：![](https://cdn.luogu.com.cn/upload/image_hosting/uqdelkdn.png)
图片 2：[](https://cdn.luogu.com.cn/upload/image_hosting/irl0hik0.png)

**Comment by YuzhenQin** [comment]
您的 Issue 重复，已被合并到 #392
