### ISSUE TITLE
在题解页面卡顿

### ISSUE THREAD

**Issue by lbr77** [extend-luogu/extend-luogu#50]
这是开了的情况
![image](https://cdn.jsdelivr.net/gh/lbr77/CDN@main/img/2021-07-28/21-47-35-ff0672.png)
下面这个是关闭后的情况
![](https://cdn.jsdelivr.net/gh/lbr77/CDN@main/img/2021-07-28/21-48-47-a27b4e.png)

**Comment by william-song-shy** [comment]
可以复现
@ForkKILLET  @optimize-2

**Comment by Minstdfx** [comment]
？

**Comment by william-song-shy** [comment]
应该是已知问题了，fixing

**Comment by Minstdfx** [comment]
嗯

**Comment by lbr77** [comment]
VER 2.10.2已修复？

**Comment by optimize-2** [comment]
还没呢 有方案了 fixing

**Comment by william-song-shy** [comment]
> 还没呢 有方案了 fixing

透露一下问题？

**Comment by optimize-2** [comment]
> > 还没呢 有方案了 fixing
> 
> 透露一下问题？

什么叫透露一下问题

**Comment by william-song-shy** [comment]
就是说下出了什么bug


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月31日(周六) 下午4:55
收件人: ***@***.***&gt;;
抄送: &quot;William ***@***.******@***.***&gt;;
主题: Re: [extend-luogu/extend-luogu] 在题解页面卡顿 (#50)




   
还没呢 有方案了 fixing
  
透露一下问题？
  
什么叫透露一下问题
 
&mdash;

**Comment by optimize-2** [comment]
> 就是说下出了什么bug
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月31日(周六) 下午4:55 收件人: ***@***.***&gt;; 抄送: &quot;William ***@***.******@***.***&gt;; 主题: Re: [extend-luogu/extend-luogu] 在题解页面卡顿 (#50) 还没呢 有方案了 fixing 透露一下问题？ 什么叫透露一下问题 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

没有 bug 就是代码性能问题
