### ISSUE TITLE
开启sponsor-tag时访问页面微卡顿

### ISSUE THREAD

**Issue by zhetengtiao** [extend-luogu/extend-luogu#51]
打开[某一个非常长的剪贴板](https://www.luogu.com.cn/paste/c8wb3geg)时停一下，会提示“页面没有响应”
这种情况在开启exlg的模块sponsor-tag的时候出现
**exlg 2.9.4也一样**

**Comment by Minstdfx** [comment]
我这里也复现了，刚准备交issue

**Comment by Minstdfx** [comment]
关掉该模块就没有这个bug    
初步推断可能是由于长剪贴板里有大量可以触发钩子里面jq选择器但又不是用户名的元素

**Comment by Minstdfx** [comment]
\> `$("span:has(a[target='_blank'][href]):not(.hover):not(.exlg-sponsor-tag)").length`
\< `22`
不至于啊说明不是这个原因

**Comment by Minstdfx** [comment]
直接让`sponsor-tag`的钩子`return 0`之后就没有这个问题了  
说明确实是这方面的问题，具体还要再看

**Comment by Minstdfx** [comment]
加了一些调试代码，希望可以找到原因.

**Comment by Minstdfx** [comment]
`using sponser-tag`还是只输出了一次啊淦   
我人傻了

**Comment by Minstdfx** [comment]
【管理员】 【前端/代码】超级可耐滴 minstdfx 酱 22:58:44  
我可能知道原因了  

【管理员】 【前端/代码】超级可耐滴 minstdfx 酱 22:59:05  
应该是本身的jq需要遍历所有元素才能确定要找的元素  

【管理员】 【前端/代码】超级可耐滴 minstdfx 酱 22:59:10  
然后  

【管理员】 【前端/代码】超级可耐滴 minstdfx 酱 22:59:31  
o2写钩子又是domnodeinsert/remove  

【管理员】 【前端/代码】超级可耐滴 minstdfx 酱 22:59:42  
钩子里面又一大堆选择器搜索  

【管理员】 【前端/代码】超级可耐滴 minstdfx 酱 22:59:49  
每次都是o(n)  

【管理员】 【前端/代码】超级可耐滴 minstdfx 酱 22:59:59  
妈的  

【管理员】 【前端/代码】超级可耐滴 minstdfx 酱 23:00:08  
但为什么去掉一个模块就好了  

【管理员】 【前端/代码】超级可耐滴 minstdfx 酱 23:01:03  
我在想钩子里面的jq判断可不可以用e.target的判断代替

**Comment by Minstdfx** [comment]
明天晚上有时间再说吧~

**Comment by 5ab-juruo** [comment]
确实，开启题解时卡顿极其明显

**Comment by optimize-2** [comment]
同 #50
