### ISSUE TITLE
feat req: 禁用不需要的功能

### ISSUE THREAD

**Issue by StudyingFather** [extend-luogu/extend-luogu#56]
有些功能并不是用户需要的，开启这些功能可能会增加内存占用和 CPU 负担。

因此希望能增加一个设置，让用户选择性地禁用一些功能。

另外这脚本究竟有多少 extend 之处啊，能不能详细在 README 里介绍一下（

**Comment by william-song-shy** [comment]
禁用的话点私信旁的exlg，在新页面选择不需要的即可

**Comment by william-song-shy** [comment]
全部功能也在那个页面

**Comment by optimize-2** [comment]
右上角 exlg 点一下
