### ISSUE TITLE
关于犇犇榜的显示问题

### ISSUE THREAD

**Issue by qwqAutomaton** [extend-luogu/extend-luogu#64]
![](https://gitee.com/hassium/res/raw/master/imgs/exluogu-issue.jpg)

如图圈起来的地方，当用户名过长时会导致犇犇计数错位。

建议改进：对于过长的用户名可以用省略号截断，如站长的可以是 “kkksc……”。

**Comment by orz001** [comment]
图挂了/xk重新放上去

![](https://hassium.gitee.io/res/imgs/exluogu-issue.jpg)

**Comment by Fununugugu** [comment]
资瓷

**Comment by optimize-2** [comment]
犇犇榜服务关闭。
