### ISSUE TITLE
关于 exlg 设置中的安全隐患

### ISSUE THREAD

**Issue by qwqAutomaton** [extend-luogu/extend-luogu#71]
在设置（就是在上边栏中的 `exlg` 按钮）里面 “code-block-ex” -> “Code Block Title” 中可以直接输入 html。所以可能会出现 XSS 之类的安全隐患？

我想到的解决方案：在设置中将输入的特殊字符（特别是 `<` 和 `>` 等）转化成 html 字符实体编码然后再进行后续的处理。

**Comment by optimize-2** [comment]
别人又动不了你本地设置

不会有人自己注入自己吧
