### ISSUE TITLE
[BUG]: help 命令显示错误

### ISSUE THREAD

**Issue by keywet06** [extend-luogu/extend-luogu#72]
`/help cc` 会显示如下消息 ：
en: `cc [name: char] jump to [name], "h|p|c|r|d|i|m|n" stands for home|problem|record|discuss|I myself|message|notification. or jump home.`
zh: `cc [name: char] 跳转至 [name]，"h|p|c|r|d|i|m|n" 代表：主页|题目|评测记录|讨论|个人中心|私信|通知。空则跳转主页。`

左侧有8个简写，右侧有7个解释

应该改为：
en: `cc [name: char] jump to [name], "h|p|c|r|d|i|m|n" stands for home|problem|contest|record|discuss|I myself|message|notification. or jump home.`
zh: `cc [name: char] 跳转至 [name]，"h|p|c|r|d|i|m|n" 代表：主页|题目|比赛|评测记录|讨论|个人中心|私信|通知。空则跳转主页。`

**Comment by optimize-2** [comment]
好 周末修
