### ISSUE TITLE
讨论版面被不正常地缩小

### ISSUE THREAD

**Issue by YOYO-UIAT** [extend-luogu/extend-luogu#80]
洛谷最近将主页上的讨论版从 12 个帖子改成了 16 个帖子，但 exlg 开启的情况下仍然只有 12 个。

**Comment by william-song-shy** [comment]
可复现

**Comment by william-song-shy** [comment]
关掉 mainpage-discuss-limit 即可

**Comment by YOYO-UIAT** [comment]
所以为啥要有这个功能……或者说能不能默认关闭

**Comment by qwqAutomaton** [comment]
> 
> 
> 所以为啥要有这个功能……或者说能不能默认关闭

那么我记得o2之前说过主页讨论扩容之后非常不爽 所以就做了这个数量限制

之后等滑动条写好了就应该可以在设置里面调整数量了
