### ISSUE TITLE
关于 @require 源

### ISSUE THREAD

**Issue by EarthMessenger** [extend-luogu/extend-luogu#81]
https://github.com/extend-luogu/extend-luogu/blob/db81e7f20b016f9c270e53d672f5ddf2555963a8/extend-luogu.user.js#L22

建议将其中 greasyfork 的安装源改为 jsdelivr

```
// @require        https://cdn.jsdelivr.net/gh/ForkKILLET/TM-dat@main/TM-dat.user.js
```

用 jsdelivr cdn 加速安装，毕竟这 greasyfork 访问速度太玄学。

**Comment by optimize-2** [comment]
将在 3.0.0 修复。
