### ISSUE TITLE
回帖表情栏的“隐藏”按钮 alt 错误（为“粗体”）

### ISSUE THREAD

**Issue by oier-namespace-std** [extend-luogu/extend-luogu#95]
见下图
![image](https://user-images.githubusercontent.com/72639018/141713140-4e22cb42-f0e3-4e73-bf75-7034a366ec3f.png)

**Comment by ren-yc** [comment]
这细节错误，，，

**Comment by ForkKILLET** [comment]
已经修了但迟迟没 merge
