### ISSUE TITLE
建议题库页面过滤已 AC 题目

### ISSUE THREAD

**Issue by warshon** [extend-luogu/extend-luogu#97]
如题：
建议支持在“题库”页面（ https://www.luogu.com.cn/problem/list ）
过滤已AC题目

**Comment by ren-yc** [comment]
Cu，建议 随机 ex 时不跳转已 AC 题目

**Comment by 5ab-juruo** [comment]
现在最多只能做到隐藏已 AC 题目，否则要巨大的访问量。

**Comment by warshon** [comment]
> 现在最多只能做到隐藏已 AC 题目，否则要巨大的访问量。

能做到这一步，也挺好了。赞！
