### ISSUE TITLE
更改代码块标题无反应

### ISSUE THREAD

**Issue by wangr-x** [extend-luogu/extend-luogu#99]
欲通过更改 exlg dash board-> code-block-ex -> Code Block Title 来修改代码块标题，但是没有反应
 希望默认去掉“源代码”三个字，只保留语言和复制键

**Comment by ren-yc** [comment]
你可以在 1800 行左右的 `code_block_title : { ty: "string", dft: "源代码 - ${lang}", info: [ "Custom Code Title", "自定义代码块标题" ] },` 中把 `源代码` 删除

**Comment by wangr-x** [comment]
找到了，问题不是在 1800 行，而是 1843 行，希望能修一下。

**Comment by 5ab-juruo** [comment]
这是可以自行修改的，不需要修改默认值来解决问题。

**Comment by 5ab-juruo** [comment]
> 欲通过更改 exlg dash board-> code-block-ex -> Code Block Title 来修改代码块标题，但是没有反应 希望默认去掉“源代码”三个字，只保留语言和复制键

请具体描述如何无反应。

**Comment by wangr-x** [comment]
就是删空之后，代码块标题会留下默认的“源代码”三个字

**Comment by optimize-2** [comment]
改成 ${lang}
不会用就先问明白再发 issue

**Comment by wangr-x** [comment]
然而假如连语言都不保留的话仍然不行
